---
output: pdf_document
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
---

Dear *Editor*

We are excited to submit our manuscript entitled 'Ecosystem size and complexity dictate riverine biodiversity' to PNAS. Given the unprecedented rate of global biodiversity loss, a crucial task for ecologists is to guide conservation efforts by identifying key environmental factors that regulate biodiversity. A prevailing wisdom suggests that species diversity is primarily demined by area; larger ecosystems support more species (i.e., the Species Area Relationship; SAR). This ecological pattern has been found in many taxa and geographic regions, forming the foundation of current conservation schemes. For example, conservation ecologists have used SAR estimates to design marine and terrestrial protected areas, which encompass more than 30 million km2 globally. However, what is largely overlooked in current biodiversity research is the role of a 'scale-invariant' complexity of ecosystem's geometric structure (hereafter, 'ecosystem complexity'). Since ecosystem complexity is independent of spatial scale or ecosystem size, existing theories are inappropriate to predict biodiversity patterns in spatially complex ecosystems.

Here, we offer a synthetic framework integrating ecosystem size and complexity influences on biodiversity patterns in branching ecosystems, including rivers, trees, and mountain ranges, to name just a few. In this widespread yet largely overlooked fractal ecosystem's geometry, branching patterns remain constant across a wide range of spatial scales. Even so, the complexity of branching patterns forms a physical template providing a wide spectrum of environmental niches for living organisms. In this research, using theory and extensive fish community data from two distinct geographic regions, **we found that ecosystem size and complexity play comparable roles in regulating riverine biodiversity; ecosystem size alone was insufficient to predict biodiversity patterns.** Larger and more branched 'complex' river networks supported greater species richness due to increased space and habitat heterogeneity. In particular, the effect of ecosystem complexity was striking in its magnitude. A unit increase of ecosystem complexity (the prevalence of branching) resulted in an increase of species diversity that would require 1911 km2 in the areal area. Further, these patterns have consistently emerged regardless of ecological traits of species and geographic regions, suggesting that the dual control of riverine biodiversity may be pervasive across taxonomic groups and geographic regions.

Our research will attract a broad audience of PNAS for the following reasons. First, our proposed framework may apply beyond branching ecosystems as both ecosystem size and complexity represent a physical template of the ecosystem's environmental heterogeneity. Second, the results of the present study provide the ecological foundation for complexity-based ecosystem management - an important perspective overlooked in the current schemes of biodiversity conservation. Hence, we have confidence that our research not only provides fundamental insights into regulating factors of biodiversity but also has far-reaching implications for biodiversity conservation.

This work is original and is not under consideration in any other journal. All authors agree with the content and with the submission for publication, and all appropriate ethical and other necessary approvals were obtained for this research. We look forward to your reply and hope that you find our article suitable for publication in your journal.

Sincerely,

Akira Terui, Ph.D. (corresponding author)
