---
title: "Ecosystem size and complexity dictate riverine biodiversity"
author:
- Akira Terui^[Department of Biology, University of North Carolina at Greensboro]
- Seoghyun Kim\footnotemark[1]
- Christine L. Dolph^[Department of Ecology, Evolution and Behavior, University of
  Minnesota]
- Taku Kadoya^[National Institute for Environmental Studies]
- Yusuke Miyazaki^[Shiraume Gakuen University]
output:
  word_document: default
  html_notebook: default
abstract: The species-area relationship, a tendency in which species richness increases with increasing area, is a ubiquitous pattern[@lomolinoEcologyMostGeneral2000] and has formed the basis of area-based conservation strategies[@desmetUsingSpeciesareaRelationship2004; @neigelSpeciesareaRelationshipsMarine2003]. However, many ecosystems possess a complex spatial structure that cannot be represented by area (the scale-invariant complexity)[@rodriguez-iturbeFractalRiverBasins2001; @turnerLandscapeEcologyTheory2015], and its role in scaling biodiversity is largely unknown. Here, we use theory and empirical analysis of extensive fish community data to show that ecosystem size and complexity jointly regulate biodiversity in rivers. Rivers are a prime example of fractal branching networks where the recurrent merging of diverse streams generates a pronounced self-similarity in complex branching patterns[@rodriguez-iturbeFractalRiverBasins2001]. Ecosystem complexity, which we define as the probability of branching per unit river distance[@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014], should increase watershed-scale species richness by increasing habitat heterogeneity. Meanwhile, ecosystem size should dictate metacommunity size and total habitat diversity, two factors that regulate watershed-scale species richness[@hubbellUnifiedNeutralTheory2001; @kallimanisHowDoesHabitat2008]. Metacommunity simulations in branching networks predicted biodiversity patterns consistent with our hypothesis. Larger and more branched ecosystems supported greater species richness at the watershed scale, and the importance of spatial difference in species composition was apparent when simulated species dispersal is limited. Cross-watershed comparisons across two geographic regions (the Hokkaido island in Japan and the midwestern US) provided empirical support for the theoretical predictions. In both regions, watershed-scale species richness increased with ecosystem size (watershed area) and complexity (branching probability) through enhanced spatial difference in species composition. Recognizing the dual control of biodiversity should broaden viable options for spatial planning of protected areas or restoration, thereby helping conserve biodiversity from societal demands that threaten it.
bibliography: reference.bib
csl: nature.csl
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
---

```{r setup, include=FALSE}

pacman::p_load(tidyverse, sf)

## read gis files
filename <- list.files(path = here::here('/empirical/data_gis'), full.names = T)
wsd_subset <- lapply(filename[str_detect(filename, "wsd_subset")], st_read)
point_subset <- lapply(filename[str_detect(filename, "point_subset")], st_read)
shape <- lapply(filename[str_detect(filename, "shape")], st_read)
shape[[1]] <- st_set_crs(shape[[1]], st_crs(wsd_subset[[1]]))

## read theory file
dat_sim <- read_csv(here::here('/theory/result/result_sim2020-11-10.csv'))

n_scenario <- dat_sim %>% distinct(n_species,
                     mean_env_source,
                     sd_env_source,
                     rho,
                     asymmetry_factor,
                     min_optim,
                     max_optim,
                     sd_env_lon,
                     theta,
                     K0,
                     sd_env,
                     spatial_env_cor,
                     phi,
                     min_niche_width,
                     max_niche_width,
                     niche_cost,
                     p_dispersal,
                     min_alpha,
                     max_alpha) %>% 
  nrow()

# for bayes factor
source(here::here('/empirical/analysis_lm_bf.R'))

# Hokkaido data
dat_hkd_site <- read_csv(here::here('/empirical/data_out/dat_hkd_site.csv'))

# Midwest data
dat_mw_site <- read_csv(here::here('/empirical/data_out/dat_mw_site.csv')) %>% 
  mutate(Year = format(as.Date(Date, format = '%m/%d/%Y'), "%Y"))

```

# Maintext

Ecologists have long sought to understand the general drivers of biodiversity. One of the most robust empirical generalizations in ecology is the positive relationship between species richness and area, i.e., the species-area relationship (the SAR)[@lomolinoEcologyMostGeneral2000]. In 1921, Arrhenius[@arrheniusSpeciesArea1921] formulated the SAR as a power-law $S = cA^z$, an equation currently known as the Arrhenius species-area relationship ($S$ is the number of species observed in a given geographic area $A$, $c$ the constant, and $z$ the scaling exponent). Since then, the spatial scaling of species richness has been observed in many taxonomic groups[@triantisIslandSpeciesareaRelationship2012]. The SAR is ubiquitous because multiple mechanisms produce an apparently similar pattern. Larger ecosystems typically support more diverse metacommunities due to increased habitat diversity[@kallimanisHowDoesHabitat2008], larger metacommunity size[@hubbellUnifiedNeutralTheory2001], and/or enhanced colonization dynamics[@lososTheoryIslandBiogeography2009]. Importantly, the SAR provides the foundation for global conservation efforts[@myersBiodiversityHotspotsConservation2000; @desmetUsingSpeciesareaRelationship2004;@neigelSpeciesareaRelationshipsMarine2003]. For example, conservation ecologists have used SAR estimates to design marine and terrestrial protected areas[@desmetUsingSpeciesareaRelationship2004; @neigelSpeciesareaRelationshipsMarine2003], which currently encompass more than 30 million km^2^ globally[@deguignet2014UnitedNations2014].

Many ecosystems, however, possess a complex spatial structure that cannot be represented by area - a dimension referred to as scale-invariant complexity[@turnerLandscapeEcologyTheory2015;@rodriguez-iturbeFractalRiverBasins2001]. Such complexity is evident in branching ecosystems, including rivers, trees, and mountain ranges, to name just a few[@rodriguez-iturbeFractalRiverBasins2001]. Geomorphic or biological processes generate a pronounced self-similarity in complex branching patterns such that the part and the whole look alike[@rodriguez-iturbeFractalRiverBasins2001]. Even though the branching structure is independent of spatial scale, it forms a physical template that dictates habitat diversity and dispersal corridors for living organisms[@grantLivingBranchesPopulation2007]. Limited, but accumulating evidence suggests that classical metapopulation and metacommunity theories cannot predict ecological dynamics driven by branching structure[@carraraDendriticConnectivityControls2012; @faganConnectivityFragmentationExtinction2002; @teruiMetapopulationStabilityBranching2018;@brownDendriticNetworkStructure2010], and this recognition has led to recent developments of spatial theories devoted to complex branching ecosystems[@rinaldoRiverNetworksEcological2018;@petersonModellingDendriticEcological2013]. For example, these studies have highlighted key roles of branching structure in driving local biodiversity patterns, such as increased species richness at merging points of branches[@carraraDendriticConnectivityControls2012]. However, most research has explored the consequences of branching complexity for local community structure[@brownDendriticNetworkStructure2010; @carraraDendriticConnectivityControls2012] or has relied solely on theoretical arguments with limited replications of branching architecture[@holtRoleBranchingMaintenance2018]. At present, we lack a comprehensive evaluation of how branching complexity scales biodiversity at the metacommunity level. Filling this knowledge gap may provide common ground for achieving successful conservation in spatially complex ecosystems, where accelerated species loss threatens the delivery of ecosystem services[@dudgeonFreshwaterBiodiversityImportance2006].

Here, we hypothesize that ecosystem size and complexity dictate biodiversity patterns in rivers - a prime example of complex branching ecosystems. The recurrent merging of diverse streams and rivers produces larger, ecologically distinct channels, ultimately forming a fluvial network with fractal branching patterns[@rodriguez-iturbeFractalRiverBasins2001]. As such, the complexity of branching structure, which we define here as the probability of branching per unit river distance[@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014], should control the ecosystem's habitat heterogeneity (habitat diversity per unit area). Meanwhile, ecosystem size (watershed area) should determine the metacommunity size and total habitat diversity (area x heterogeneity). We predict that ecosystem size and branching complexity increase watershed-scale species richness ($\gamma$ diversity) by enhancing local species richness ($\alpha$ diversity) and/or spatial difference of species composition ($\beta$ diversity) under different ecological scenarios. The present study combines theory and empirical analysis of extensive community data from two different regions of the globe to provide crucial insights into how ecological communities are structured in complex branching networks.

First, we theoretically analyzed the influences of ecosystem size and branching complexity on $\gamma$ diversity. We depicted branching ecosystems as a spatial network of connected habitat patches which local communities inhabit[@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014] (**Figure 1**). Two factors determine mean environmental conditions at each habitat patch: (1) headwater environments (the most upstream habitat patch) and (2) local environmental noise. Environmental values at headwaters are drawn randomly from a normal distribution and propagate downstream with local environmental noise (i.e., a spatial autoregressive process with white noise). These environmental values recurrently 'mix' at confluences considering the relative size of joining tributaries (see **Methods**). Therefore, our network-generation procedure resembles natural processes of how branching river networks create diverse habitats in a metacommunity. We then simulated metacommunity dynamics in the theoretical branching networks using a general metacommunity framework[@thompsonProcessbasedMetacommunityFramework2020]. In this model, 50 species with different abiotic niches (optimum and width) disperse along a network and compete for resources with varied strengths in temporally dynamic environments (see **Methods** for model details).

Given the results of extensive sensitivity analysis (**Supplementary Information**), we considered `r n_scenario` simulation scenarios comprising a combination of four landscape and eight ecological scenarios. We distinguished landscape scenarios by setting four combinations of environmental variation at headwaters ($\sigma_h =$ `r unique(dat_sim$sd_env_source)`) and the degree of local environmental noise ($\sigma_l =$ `r unique(dat_sim$sd_env_lon)`), both of which are defined as standard deviations of normal distributions. When $\sigma_h > \sigma_l$, branching produces greater habitat heterogeneity because headwaters are the primary source of environmental variation. This landscape scenario should reproduce natural patterns of habitat heterogeneity, in which environmental conditions differ greatly among tributaries[@mooreEmergentStabilityLarge2015; @petersonModellingDendriticEcological2013]. In the meantime, when $\sigma_h \le \sigma_l$, local environmental noise masks environmental variation among tributaries, leading to minimal influences of branching on habitat heterogeneity. This scenario may reflect human-modified landscapes where the physical or biological distinctiveness of tributaries has been compromised due to human activities[@poffHomogenizationRegionalRiver2007; @teruiMetapopulationStabilityBranching2018]. Thus, the inequality between $\sigma_h$ and $\sigma_l$ creates contrasting patterns of habitat heterogeneity within a network. We also considered eight ecological scenarios that differ in dispersal distance (controlled by the rate parameter of an exponential dispersal kernel), dispersal probability, and the maximum value of interspecific competition strength (see **Methods**). These simulation scenarios were capable of reproducing common spatial patterns of local species richness in rivers, corroborating the appropriateness of our choice in parameter combinations (**Supplementary Information**). Under each simulation scenario, we simulated 1400 time steps of metacommunity dynamics (including 400 time steps of initialization and burn-in periods) in `r max(dat_sim$n_rep)` branching networks with the gradients of ecosystem size (the number of habitat patches: `r min(dat_sim$n_patch)` to `r max(dat_sim$n_patch)`) and complexity (branching probability: `r round(min(dat_sim$p_branch), 2)` to `r round(max(dat_sim$p_branch), 2)`).

Our theoretical analysis yielded results consistent with our prediction. Ecosystem size and complexity both increased $\gamma$ diversity under a realistic landscape scenario (**Figures 2 and 3**), where the environmental variation at headwaters ($\sigma_h$) is greater than the degree of local environmental noise ($\sigma_l$). The relationships had a characteristic of power-law (i.e., linear in a log-log scale) and were consistent under various ecological scenarios. The strength of competition and dispersal processes (dispersal distance and probability) did not change the relationships between $\gamma$ diversity and ecosystem properties (compare panels in **Figures 2 and 3**). Hence, the ecosystem size and complexity are expected to increase $\gamma$ diversity regardless of ecological scenarios.

However, dispersal processes affected mechanisms that underlie the positive effects of ecosystem size and complexity on $\gamma$ diversity (compare left and right columns in **Figures 2 and 3**). We observed a greater contribution of $\beta$ diversity (defined as $\frac{\gamma}{\alpha}$) to increased $\gamma$ diversity when dispersal limitation exists (i.e., species travel short distances). This pattern reflects significant spatial difference of species composition over the branching network. In contrast, when the dispersal limitation was relaxed (species travel long distances), a clear increase in $\alpha$ diversity underpinned the positive relationships between $\gamma$ diversity and ecosystem properties. The results agree with previous predictions that increased dispersal homogenizes community composition while enhancing local diversity through increased immigrants from suitable habitat patches (i.e., mass effects)[@thompsonProcessbasedMetacommunityFramework2020]. These patterns were consistent across different levels of dispersal probabilities (**Figures S5 and S12**). The strength of competition decreased the maximum of $\alpha$ diversity but did not change the scaling relationships with ecosystem properties (**Figures 2 and 3**). In summary, our theory highlights how apparently similar patterns in $\gamma$ diversity emerge through different ecological pathways.

Influences of ecosystem size and complexity differed significantly in their dependence on landscape scenarios. Ecosystem size had positive effects on $\gamma$ diversity regardless of landscape scenarios, although the slopes were steeper with greater environmental variation (higher $\sigma_h$ and/or $\sigma_l$) (**Figures 2 and S5-11**). This result is attributable to the fact that larger ecosystems can hold more individuals in a metacommunity[@hubbellUnifiedNeutralTheory2001]. In contrast, we observed limited or no influences of branching complexity when local environmental noise was equal to or exceeded environmental variation at headwaters ($\sigma_l \ge \sigma_h$; **Figures S13-18**). Under this scenario, branching may not contribute to the ecosystem's habitat heterogeneity because local environmental noise masks environmental differences between tributaries. Therefore, this landscape scenario decouples the intimate relationship between branching structure and habitat heterogeneity, thereby eliminating the positive effect of branching complexity on $\gamma$ diversity. This theoretical prediction may not apply to pristine or semi-natural river networks where individual streams with diverse geological and/or climatic backgrounds show distinct environmental conditions, including water temperature, water chemistry, and flow/sediment regimes[@petersonModellingDendriticEcological2013; @mooreEmergentStabilityLarge2015]. Instead, it may be more relevant to severely altered landscapes where human disturbance compromises the environmental distinctiveness of branches through, for example, flow regulations by dams[@poffHomogenizationRegionalRiver2007]. Hence, our theory has important implications for riverine biodiversity conservation by pointing to the crucial role of habitat diversity produced by branching structure.

The proposed theory provided important insights into how ecological communities are structured in branching networks; however, empirically testing the predictions is extremely difficult because it requires metacommunity-level replications. To confront this logistical challenge, we compiled fish community data across two geographic regions: the Hokkaido island in Japan and the midwestern US (Midwest). These regions are located in comparable latitude ranges but support distinct fish communities (**Figure 1**). Therefore, this data set provides an excellent opportunity to examine the generality of our theoretical predictions. After careful data selection (see **Methods** and **Supplementary Information**), we estimated $\alpha$, $\beta$, and $\gamma$ diversity (asymptotic species richness; **Methods**) at `r nrow(wsd_subset[[1]]) + nrow(wsd_subset[[2]])` watersheds (`r nrow(wsd_subset[[1]])` in Hokkaido and `r nrow(wsd_subset[[2]])` in the Midwest), each of which comprised $\ge$ 10 sites of presence-absence fish community data (a total of `r nrow(point_subset[[1]]) + nrow(point_subset[[2]])` sites). We considered watersheds as independent replicates of metacommunities if the river network flows into one of the following: the ocean, a large lake/reservoir ($\ge$ 10 km² in the areal area), or a large river that may represent lentic habitats ($\ge$ 5000 km² in the watershed area). We combined this data set with geospatial information (watershed area, branching probability, annual mean temperature, annual cumulative precipitation, the fraction of forest, and dam density) to examine potential influences of macro-scale drivers of species diversity. Using this data set, we assessed whether observed patterns are consistent across the two geographic regions by developing global and region-specific models. In the global model, we assumed that effects of ecosystem size (watershed area) and complexity (branching probability) are constant across the two regions (i.e., fixed slopes). Meanwhile, the region-specific model assumes region-specific slopes of ecosystem size and complexity (**Methods**). We compared the support of these competing models using the Bayes factor, a measure of the strength of evidence in favor of one model over the alternative. In our definition (**Methods**), the Bayes factor of $> 1$ indicates the support for the global model over the region-specific model.

Despite the substantial difference in fish fauna between the study regions, we found strong support for the global model in explaining $\gamma$ diversity (Bayes factor = `r round(fit$gamma$bayes_factor, 1)`): this result suggests the consistent effects of ecosystem size and complexity on $\gamma$ diversity across the two geographic regions. Furthermore, the observed patterns were closely aligned with our theoretical predictions (**Table 1 and Figure 4**). The estimated $\gamma$ diversity increased with increasing watershed area (ecosystem size) and branching probability (ecosystem complexity) across watersheds. These effects remained significant even after controlling for the potential influences of other environmental factors (precipitation, temperature, the fraction of forest, and dam density) (**Table 1**). Overall, our statistical analysis provides strong empirical evidence that ecosystem size and complexity jointly scale riverine biodiversity at the metacommunity level.

Similarly, we found weak to moderate supports for the global models of $\alpha$ and $\beta$ diversity (Bayes factor = `r round(fit$alpha$bayes_factor, 1)` and `r round(fit$beta$bayes_factor, 1)`, respectively). In both regions, $\beta$ diversity responded significantly to ecosystem size and complexity while $\alpha$ diversity showing a weaker or a vague response to these ecosystem properties (**Table 1 and Figure 4**). In our simulations, this pattern has emerged under the scenarios with dispersal limitation, which elegantly matches the previous observations of stream fish movement. Field studies (e.g., mark-recapture) recurrently revealed the restricted movement of stream fish, typically limited to several tens to hundreds of meters[@radingerPatternsPredictorsFish2014]. The reciprocal agreement of theoretical and empirical patterns provides indirect but convincing evidence that dispersal limitation plays a key role in driving the associations between $\gamma$ diversity and ecosystem properties in rivers.

The consistent effect of branching probability on $\gamma$ diversity across the study regions is noteworthy because the watersheds in the Midwest are severely altered by agriculture (median % agricultural land use: `r round(median(wsd_subset[[2]]$frac_agri)*100)`% in the Midwest and `r round(median(wsd_subset[[1]]$frac_agri)*100)`% in Hokkaido). If the intensive land use by humans causes significant homogenization of in-stream habitat conditions among tributaries, theory predicts a weakened effect of branching probability on $\gamma$ diversity. However, $\gamma$ diversity increased significantly with increasing branching probability in this highly modified landscape, suggesting that tributaries still sustain unique environmental conditions to support high spatial difference of species composition. In support of this interpretation, $\beta$ diversity increased with increasing branching probability in both regions (**Figure 4**). It is conceivable that local geological and geomorphological differences, such as slope, aspect, and soil porosity, persist in human-dominated landscapes to maintain the diversity of in-stream processes among tributaties. Although our analysis is correlative, the finding is encouraging because the branching complexity of river networks may serve as a natural defense system to human-induced environmental changes.

There may be confounding factors that are not incorporated into our statistical models. However, we are confident in our statistical inference because the observed patterns were fairly consistent with our theoretical predictions that are free from any confounding effects. Further, our fitted models generally showed high R^2^ values ($\alpha$ diversity: `r round(summary(fit$alpha$model)$r.squared, 2)`; $\beta$ diversity, `r round(summary(fit$beta$model)$r.squared, 2)`; $\gamma$ diversity `r round(summary(fit$gamma$model)$r.squared, 2)`). Therefore, it is very unlikely that spurious correlations are responsible for our results.

The emerging complexity-diversity relationship points to several important avenues for riverine biodiversity conservation. First and foremost, there is now a clear need to explicitly consider the dimension of ecosystem complexity to achieve successful conservation. Human-induced habitat alterations, including flow regulation[@poffHomogenizationRegionalRiver2007], landscape modification[@finlayStreamSizeHuman2011; @grillMappingWorldFreeflowing2019], and stream burial[@elmoreDisappearingHeadwatersPatterns2008], may compromise or restrict access to the diverse habitats that complex branching networks may support. Hence, it is imperative to recognize the role of branching complexity and minimize the homogenizing effects of human activities. Second, the complexity perspective may provide insights into the spatial planning of conservation efforts. Riverine reserves and local restoration are increasingly recognized as an effective management tool, and designing a spatial network of conservation sites in rivers is an area of active research[@koningNetworkGrassrootsReserves2020]. While large reserves or restoration sites are undoubtedly important, our results indicate the potential of coordinated networks of local conservation sites in protecting biodiversity. For example, synergies of multiple small reserves may emerge at the watershed scale when ecologically-distinct tributaries are involved in the design, as evidenced by the recent successful conservation of tropical fishes in Thailand's Salween basin[@koningNetworkGrassrootsReserves2020].

While the prevailing evidence supports the importance of ecosystem size in scaling species diversity, ecosystem complexity has not received the attention it deserves. However, the ubiquity of scale-invariant complexity across terrestrial[@turnerLandscapeEcologyTheory2015] and aquatic ecosystems[@rodriguez-iturbeFractalRiverBasins2001] calls for more research embracing the two orthogonal dimensions of the ecosystem's geometric structure. Our fundamental findings of the dual control of biodiversity should apply beyond branching ecosystems because ecosystem size and complexity both represent a physical 'template' providing a wide spectrum of niche opportunities for living organisms. The dual dimensional approach - size and complexity - broadens viable options for spatial planning of protected areas or restoration sites, thereby helping conserve biodiversity from societal demands that threaten it. The generalization of our findings in spatially complex ecosystems represents a frontier for future research.


# Methods

## Theory

### Network generation

We depicted branching ecosystems as a bifurcating network of connected habitat patches[@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014] (**Figure 1**). Habitat patches, or local communities, can be either non-branching or branching river sections with a unit length $l$, which defines the scale of local species interactions. Two parameters determine the geometric properties of simulated branching networks: the number of habitat patches $N_p$ (ecosystem size) and branching probability $P_b$ (ecosystem complexity). Each habitat patch is assigned to be a branching patch (including upstream terminals) with probability $P_b$ or a non-branching patch with probability $1-P_b$. In this framework, an individual branch is a consecutive series of non-branching patches terminated at a branching patch; therefore, the number of habitat patches in branch $q$, $n_{p,q}$, is a realization of a random variable drawn from a geometric distribution $n_{p,q} \sim Ge(P_{b})$[@teruiMetapopulationStabilityBranching2018] but conditional on $\sum_{q=1}^{N_b}n_{p,q} = N_p$ ($N_b$ is the number of branches in a network). The number of branches $N_b$ is identical to the number of branching habitat patches in a network, or the number of 'success' out of $N_p$ trials. This leads to an assumption that $N_b$ is a realization of a random variable drawn from a binomial distribution as $N_b \sim Binomial(N_p, P_b)$. This framework has two merits. First, it reflects observed patterns of branch length distribution, which is known to follow an exponential distribution (a continuous version of a geometric distribution)[@rodriguez-iturbeFractalRiverBasins2001]. Second, it preserves the fractal nature of branching patterns[@peckhamReformulationHortonLaws1999]. An alternative approach is the use of optimal channel networks[@carraroGenerationApplicationRiver2020]. However, we employed our framework because branching probability $P_b$ is quantifiable in natural river networks, enabling us to compare theoretical predictions with empirical observations.

In our network generation, we first drew $N_b$ from the binomial distribution but selected an odd number to constitute a bifurcating branching network. We then determined $n_{p,q}$ as random draws from the geometric distribution with the constraint of $\sum_{q=1}^{N_b}n_{p,q} = N_p$. The generated branches were organized randomly into a bifurcating branching network.

Two sources of variation characterize the long-term average of the abiotic environment at each habitat patch: environmental variation at headwaters ($\sigma_h$) and local environmental noise ($\sigma_l$). We drew random values from a normal distribution with a mean of zero and a standard deviation of $\sigma_{h}$ and assigned them to headwater patches (i.e., the most upstream patches). These environmental values at headwaters propagate downstream through a spatial autoregressive process defined as:

$$
\mu_{z,k} = \rho \mu_{z,k+1} + \epsilon_{k}
$$

where $\mu_{z,k}$ is the mean environmental value at longitudinal position $k$ ($k$ is the network distance from the outlet patch; $k = 1$ at the outlet), $\rho$ is the strength of spatial autocorrelation and $\epsilon_k$ is the local environmental noise that follows a normal distribution with a mean of zero and a standard deviation of $\sigma_l$. The parameter $\rho$ can take values of $0-1$ with larger values indicating greater spatial autocorrelation. In this study, we set $\rho = 1$ to mimic strong spatial autocorrelation in riverine environments. At confluences, we took a weighted mean of environmental values given the relative size of upstream contributing area of joining tributaries:

$$
\begin{align}
\mu_{z,k} &= \omega(\rho \mu_{z,k+1}^R + \epsilon_{k}^R) + (1-\omega)(\rho \mu_{z,k+1}^L + \epsilon_{k}^L) \\
\omega &= \frac{A_{k+1}^R}{A_{k+1}^R + A_{k+1}^L}
\end{align}
$$
where $R$ and $L$ denote "right" and "left" branches, respectively, and $A_k$ is the number of upstream habitat patches at longitudinal position $k$ (akin to the upstream watershed area). The parameter $\omega$ takes values of $0-1$ and represents the relative influence of the right tributary given the relative size of joining tributaries. With this expression, larger tributaries have a greater influence on the downstream environment, as observed in natural river networks[@bendaNetworkDynamicsHypothesis2004].

### Metacommunity model
We simulated metacommunity dynamics in branching river networks following the metacommunity framework proposed by Thompson et al.[@thompsonProcessbasedMetacommunityFramework2020]. In this framework, abiotic environmental conditions (density-independent), intra- and interspecific competition (density-dependent), and dispersal regulate a species' realized population growth. Below, we describe the details of our metacommunity model.

The realized number of individuals $N_{ix}(t + 1)$ (species $i$ at patch $x$ and time $t+1$) is given as:

$$
N_{ix}(t + 1) \sim Poisson(n_{ix}(t) + I_{ix}(t) - E_{ix}(t))
$$
where $n_{ix}(t)$ is the expected number of individuals given the local community dynamics at time $t$, $I_{ix}(t)$ the expected number of immigrants to patch $x$, and $E_{ix}(t)$ the expected number of emigrants from patch $x$. The realized discrete number of individuals is drawn from a Poisson distribution to account for stochasticity in demographic and dispersal processes[@fronhoferClassicalMetapopulationDynamics2017; @thompsonProcessbasedMetacommunityFramework2020]. Local community dynamics are simulated based on the Beverton-Holt equation[@bevertonDynamicsExploitedFish1957]:

$$
n_{ix}(t) = \frac{N_{ix}(t)r_{ix}(t)}{1 + \frac{r_{0,i}-1}{K_{x}}\sum_{j=1}^S{\alpha_{ij}N_{jx}(t)}}
$$

where $r_{ix}(t)$ is the reproductive rate of species $i$ given the environmental condition at patch $x$ and time $t$, $r_{0,i}$ the maximum reproductive rate of species $i$, $K_{x}$ the carrying capacity at patch $x$, $\alpha_{ij}$ the competition coefficient between species $i$ and $j$, and $S$ the number of species in a metacommunity. $K_x$ was expressed as a function of the number of upstream habitat patches $A_x$ ($K_x = 100A_x$) to represent increasing habitat size with increasing upstream watershed area[@altermattRiverNetworkProperties2013; @teruiThreeEcologicalFactors2016]. The parameter $\alpha_{ij}$ represents the strength of interspecific competition relative to that of intraspecific competition: interspecific competition is greater than intraspecific competition if $\alpha_{ij}$ > 1 (intraspecific competition coefficient was set constant as $\alpha_{ii} = 1$). $\alpha_{ij}$ was drawn randomly from a uniform distribution as $\alpha_{ij} \sim Unif(0, \alpha_{max})$. The density-independent reproductive rate $r_{ix}(t)$ is affected by abiotic environments (non-consumable) and determined by the following Gaussian function:

$$
r_{ix}(t) = \delta~r_{0,i}~exp[{-\frac{\{\mu_i-z_x(t)\}^2}{2\sigma^2_{niche,i}}}]
$$
where $\mu_i$ is the optimal environmental value for species $i$, $z_x(t)$ the environmental value at patch $x$ and time $t$, and $\sigma_{niche,i}$ the niche width of species $i$. We introduced the cost of a wide niche by multiplying $\delta$[@chaianunpornEvolutionaryResponsesClimate2015]:

$$
\delta = exp(-\frac{\sigma_{niche,i}^2}{2\nu^2})
$$ 

Smaller values of $\nu$ imply greater costs of having a wider niche (i.e., decreased maximum reproductive rate) and reduce the realized reproductive rate $r_{ix}(t)$ near the niche optimum.

The environmental value at patch $x$ and time $t$, $z_x(t)$, is assumed to follow a multivariate normal distribution as $z_{x}(t) \sim MVN(\boldsymbol{\mu_z}, \boldsymbol{\Omega_z})$, where $\boldsymbol{\mu_z}$ is the vector of mean environmental conditions of habitat patches and $\boldsymbol{\Omega_z}$ is the variance-covariance matrix. The diagonal elements of the variance-covariance matrix $\sigma^2_z$ represent the degree of temporal environmental variation. The off-diagonal elements $\Omega_{xy}$ represent spatial autocorrelation in temporal environmental variation as:

$$
\Omega_{xy} = \sigma_z^2~exp(-\phi d_{xy})
$$

$\Omega_{xy}$ denotes the temporal covariance of environmental conditions between patch $x$ and $y$, which is assumed to decay exponentially with increasing distance between the patches $d_{xy}$ (the shortest network path measured as the number of habitat patches). The parameter $\phi$ determines the degree of the distance decay of environmental correlates.

The expected number of emigrants at time $t$ is the product of dispersal probability $p_d$ and $n_{ix}(t)$: $E_{ix}(t) = p_{d}n_{ix}(t)$. The immigration probability at patch $x$ for species $i$, $\xi_{ix}(t)$, is calculated using the following equation that accounts for separation distance among habitat patches and dispersal capability of a species:

$$
\xi_{ix}(t) = \frac{\sum_{y,y \neq x}E_{iy}(t)~exp(-\theta d_{xy})}{\sum_{x} \sum_{y,y \neq x}E_{iy}(t)~exp(-\theta d_{xy})}
$$
The parameter $\theta$ regulates the dispersal distance of a species that follows an exponential distribution ($\theta^{-1}$ corresponds to the expected dispersal distance). The expected number of immigrants is calculated as $I_{ix}(t) = \xi_{ix}(t)\sum_x^{N_p} E_{ix}$.

### Simulation
We used `r n_scenario` sets of parameter combinations (i.e., simulation scenarios) based on the results of extensive sensitivity analysis (**Supplementary Information**). The parameter combinations comprises four landscape and eight ecological scenarios. Landscape scenarios distinguish spatial patterns of habitat heterogeneity, while ecological scenarios change ecological traits of simulated species. For landscape scenarios, we used four combinations of environmental variation at headwaters ($\sigma_h = 0.01, 1$) and the degree of local environmental noise ($\sigma_l = 0.01, 1$). The inequality of $\sigma_h$ and $\sigma_l$ controls the coupling of branching complexity and habitat heterogeneity. For ecological scenarios, we varied three ecological parameters that are relevant for dispersal and interspecific competition: dispersal distance ($\theta =$ `r unique(dat_sim$theta)`), dispersal probability ($p_d =$ `r unique(dat_sim$p_dispersal)`), and the maximum value of competition coefficients ($\alpha_{max} =$ `r unique(dat_sim$max_alpha)`). This setup results in eight ecological scenarios with different levels of dispersal and competition.

We allowed interspecific variation in niche optimum and width, which were drawn from uniform distributions as $\mu_i \sim Unif(-1, 1)$ and $\sigma_{niche,i} \sim Unif(0.1, 1)$. We used fixed values for the following parameters: maximum reproductive rate ($r_{0,i} =$ 4), niche cost ($\nu =$ `r unique(dat_sim$niche_cost)`), the degree of temporal environmental variation ($\sigma_z =$ `r unique(dat_sim$sd_env)`), and the extent of spatial autocorrelation in temporal environmental dynamics ($\phi =$ `r unique(dat_sim$phi)`).

Under each simulation scenario, we simulated 1400 time steps of metacommunity dynamics (including 200 time steps for initialization and 200 time steps for burn-in) in `r max(dat_sim$n_rep)` branching networks with the gradients of ecosystem size (the number of habitat patches: `r min(dat_sim$n_patch)` to `r max(dat_sim$n_patch)`) and complexity (branching probability: `r round(min(dat_sim$p_branch), 2)` to `r round(max(dat_sim$p_branch), 2)`). During the first 200 time steps (an initialization period), we initialized the simulation by seeding each habitat patch with populations of each species drawn from a Poisson distribution with a mean of 0.5. We repeated the seeding every 10 time steps during the initialization to allow species to establish their populations if they can grow from low abundances. After the initialization period, we ran 200 time steps as a burn-in period with no seeding to minimize influences of initial conditions. We saved the last 1000 time steps to estimate the temporal averages of $\alpha$, $\beta$, and $\gamma$ diversity. We removed simulation replicates in which no species established populations over the initial 400 time steps (`r sum(dat_sim$alpha_div == 0)` replicates out of `r nrow(dat_sim)` replicates). Ecosystem size and complexity were drawn randomly from uniform distributions as: $N_p \sim Unif(10, 150)$ and $P_b \sim Unif(0.01, 0.99)$ ($N_p$ was rounded to the nearest integer before running simulations). Values of simulation parameters were summarized in **Table S2**. We performed simulations using R version 4.0.2[@rcoreteamLanguageEnvironmentStatistical2020].

## Empirical data analysis

### Fish community data

We compiled fish data at two geographic regions: the Hokkaido island, Japan, and the Midwest, US. For Hokkaido, we used data from the Hokkaido Freshwater Fish Database HFish[@fukushimaHokkaidoFreshwaterFish2011; @fukushimaModellingEffectsDams2007], monitoring data at protected watersheds[@comteRivFishTIMEGlobalDatabase2021; @teruiMetapopulationStabilityBranching2018], and primary data collected by the authors[@miyazakiTemporalDynamicsFluvial2016; @teruiThreeEcologicalFactors2016], which collectively cover the entire Hokkaido island. For the Midwest, we assembled fish community data collected by the Iowa Department of Natural Resources[@iowadepartmentofnaturalresourcesBiologicalAssessmentIowa2004], Illinois Environmental Protection Agency and Illinois Department of Natural Resources[@illinoisenvironmentalprotectionagencyIllinoisWaterMonitoring2014], Minnesota Pollution Control Agency[@minnesotapollutioncontrolagencyDevelopmentFishbasedIndex2014], and Wisconsin Department of Natural Resources[@wisconsindepartmentofnaturalresourcesGuidelinesAssessingFish2018]. We detailed procedures for initial data selection in **Supplementary Information**.

We considered watersheds as independent replicates of metacommunities if the river network flows into one of the following: the ocean, a large lake/reservoir ($\ge$ 10 km² in the areal area) or a large river that may represent lentic habitats ($\ge$ 5000 km² in the watershed area). These watersheds are small enough (`r round(min(c(wsd_subset[[1]]$area, wsd_subset[[2]]$area)))` to `r round(max(c(wsd_subset[[1]]$area, wsd_subset[[2]]$area)))` km^2^) to assume that fishes can disperse therein at an ecological time scale[@comteFishDispersalFlowing2018; @giamEnvironmentPredationGovern2016], while posing challenges to traverse across watersheds (the ocean or lentic habitats). Metacommunities with $\ge$ 10 sampling sites were used in our analysis because a small sample size inflates statistical uncertainties in estimating diversity metrics (**Supplementary Information**).

We estimated $\alpha$, $\beta$, and $\gamma$ diversity at each watershed. $\gamma$ diversity is the total species richness at each watershed. Since it is impossible to sample all species present in each watershed, we used asymptotic species richness as a proxy for $\gamma$ diversity. Asymptotic species richness can be interpreted as the estimated true species richness in a given area when estimated using spatial replicates of local community data within a metacommunity[@chaoRarefactionExtrapolationHill2014a; @chaseEcosystemDecayExacerbates2020]. We estimated asymptotic species richness using sampling sites located in the same watershed (i.e., spatial replicates within a metacommunity) via the R package 'iNEXT'[@hsiehINEXTPackageRarefaction2016]. We assessed the completeness of the observed species richness based on sample coverage, which is the proportion of observed species richness to asymptotic species richness. We excluded watersheds whose sample coverage was below 0.9 because the estimates of asymptotic species richness may contain non-negligible statistical uncertainty. $\alpha$ diversity was estimated by taking an average of local species richness at each site. $\beta$ diversity was estimated by dividing the estimated $\gamma$ diversity by $\alpha$ diversity[@whittakerVegetationSiskiyouMountains1960].

After the data selection procedure, we obtained diversity estimates from `r nrow(wsd_subset[[1]]) + nrow(wsd_subset[[2]])` watersheds (Hokkaido: `r nrow(wsd_subset[[1]])`, Midwest: `r nrow(wsd_subset[[2]])`), which encompassed a total of `r nrow(point_subset[[1]]) + nrow(point_subset[[2]])` sites (Hokkaido: `r nrow(point_subset[[1]])`, Midwest: `r nrow(point_subset[[2]])`). Observations ranged from `r min(dat_hkd_site$Year, na.rm = T)` to `r max(dat_hkd_site$Year, na.rm = T)` in Hokkaido and from `r min(dat_mw_site$Year, na.rm = T)` to `r max(dat_mw_site$Year, na.rm = T)` in the Midwest. Fish species observed in the final data set were listed in **Tables S5 and S6**.

### Environmental data

We collected data for watershed characteristics (watershed area [km^2^], branching probability, and mean elevation [m]), climatic variables (mean annual air temperature [degree Celsius] and cumulative precipitation [mm]), and land use (the fractions of forest, urban, and agriculture, and dam density per watershed area [km^-2^]). We used Hydrologically Adjusted Elevations of MERIT Hydro[@yamazakiMERITHydroHighResolution2019] to delineate watershed polygons and river lines (defined as $\ge$ 1 km^2^ in the watershed area), which were separated by either the ocean, large lakes/reservoirs ($\ge$ 10 km^2^ in the areal area), or large rivers ($\ge$ 5000 km^2^ in the watershed area). The ocean and large lakes/reservoirs were extracted from Global 1-second Water Body Map ver 1.0[@yamazakiDevelopmentGlobal90m2015]. Watershed area was estimated based on the delineated watershed polygons. We estimated branching probability by fitting exponential distributions to histograms of branch length (unit: kilometer, river segment between successive confluences or a confluence and the outlet/upstream terminal) as $branch~length \sim Exp(\lambda)$. A derived statistical quantity $1 − e^{−\lambda}$ corresponds to the theoretical branching probability $P_b$. We obtained the mean elevations for each watershed polygon using Hydrologically Adjusted Elevations of MERIT Hydro[@yamazakiMERITHydroHighResolution2019]. We estimated the spatial averages of mean annual air temperature and cumulative precipitation for each watershed (~1 km resolution), which were extracted from WorldClim 1.4[@hijmansVeryHighResolution2005]. We calculated the fractions of forest, urban, and agriculture for each watershed using land use data in 2015 from Copernicus Global Land Service (100-m resolution)[@marcelbuchhornCopernicusGlobalLand2020]. We calculated dam density per watershed area (km^-2^) based on the Global Reservoir and Dam Database, Version 1 (GRanDv1)[@lehnerGlobalReservoirDam2011; @lehnerHighresolutionMappingWorld2011]. We used ArcMap 10.7, SAGA 6.3.0, and the following R packages to perform geospatial analysis: 'RSAGA'[@brenningRSAGASAGAGeoprocessing2018], 'sf'[@pebesmaSimpleFeaturesStandardized2018], 'raster'[@hijmansRasterGeographicData2020], 'rgdal'[@rogerbivandRgdalBindingsGeospatial2020], 'stars'[@edzerpebesmaStarsSpatiotemporalArrays2020], and 'exactextractr'[@danielbastonExactextractrFastExtraction2020].

### Statistical analysis

We developed linear regression models to examine the effects of macro-scale drivers on diversity metrics. Log-transformed diversity metrics ($\alpha$, $\beta$ and $\gamma$ diversity) at watershed $w$, $log_{10}~y_w$, were assumed to follow a normal distribution as $log_{10}~y_w \sim Normal(\mu_w, \sigma^2)$. The parameter $\mu_w$ was related to linear predictors, including log-transformed watershed area (ecosystem size; $log_{10}~WA$), log-transformed branching probability (ecosystem complexity; $log_{10}~P_b$), region (coded as Hokkaido = 0, Midwest = 1; $region$), air temperature, precipitation, the fraction of forest land use (logit-transformed), and dam density. Although our primary focus of this analysis is to assess the effects of watershed area and branching probability, we included climate and land use variables to control their effects statistically. We did not include the fractions of urban and agricultural land use in the statistical models because these variables were strongly correlated with the fraction of forest land use (**Figure S19**). Similarly, we did not use mean elevation in the statistical models because it showed a moderate correlation with air temperature (**Figure S19**). Correlations for other combinations of explanatory variables were weak to moderate.

Climate (air temperature and precipitation) and land use (the fraction of forest and dam density) differed clearly between the regions. Therefore, we used residuals of the simple linear regressions between the climate or land use variable (response variable) and region (explanatory variable). The residuals represent deviations from the regional averages; positive values indicate values greater than the regional average while negative values indicating values smaller than the regional average.

We constructed two models for each of the diversity metrics: global and region-specific models. The global model assumes that the effects of watershed area and branching probability are consistent across geographic regions (i.e., no interactive effects of the region with other linear predictors).

$$
\mu_w = \xi_0 + \xi_1~log_{10}~WA_w + \xi_2~log_{10}~P_{b,w} + \xi_3~region_w + \sum_k \xi_k x_{k,w}
$$

where $\xi_k$ are the intercept and regression coefficients for linear predictors. Meanwhile, the region-specific model assumes the effects of watershed area and branching probability differ between regions (i.e., interactions between region and watershed area/branching probability).

$$
\begin{align}
\mu_w =& \xi_0 + \xi_1~log_{10}~WA_w + \xi_2~log_{10}~P_{b,w} + \xi_3~region_w +\\
&\xi_4~log_{10}~WA_w \cdot region_w + \xi_5~log_{10}~P_{b,w} \cdot region_w + \sum_k \xi_k x_{k,w}
\end{align}
$$
We compared the performance of these competing models using the Bayes factor[@wagenmakersPracticalSolutionPervasive2007], which gives the relative strength of evidence in favor of the global model (M0) over the region-specific model (M1). We used Bayesian Information Criteria (BIC) of the linear models to approximate the Bayes factor[@wagenmakersPracticalSolutionPervasive2007]:

$$
Bayes~factor = exp(\Delta BIC_{10}/2)
$$

where $\Delta BIC_{10} = BIC(M1) - BIC(M0)$. We performed statistical analysis using R version 4.0.2[@rcoreteamLanguageEnvironmentStatistical2020].

# Acknowledgements
We are grateful to numerous people who have been involved in the collection of fish community data. We thank Michio Fukushima and Hirokazu Urabe for providing information on the Hokkaido Freshwater Fish Database HFish and the fish monitoring data at protected watersheds in Hokkaido. This research was funded by National Science Foundation through a Water Sustainability and Climate Program (WSC) Observatory grant (EAR‐1209402): REACH (Resilience under Accelerated Change) and through a Division of Environmental Biology (DEB 2015634) and by Environmental Protection Agency through a Water Quality Benefits grant (EPA-G2015-STAR-A1). 

# Author contributions
AT conceived of the project. AT performed theoretical and statistical analysis with inputs from TK. AT, SK, CLD, and YM compiled and managed the fish community data set. AT wrote the first draft while SK, CLD, TK, and YM contributed significantly to the final version.

# Data and code availability
Third parties provided data for empirical data analysis; references are provided in the main text and Supplementary Information where appropriate. R functions for the generation of branching networks and the metacommunity simulation are provided as the R package 'mcbrnet.' (available at https://github.com/aterui/mcbrnet). Codes for simulations, statistical analysis, figures, and tables are available at https://github.com/aterui/public-proj_stream-diversity.


# References