---
title: "Emergent dual scaling of riverine biodiversity"
output: word_document
csl: pnas.csl
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
bibliography: references.bib
---

```{r setup, include=FALSE}

  pacman::p_load(tidyverse, sf)
  
  # define digits function
  op = function(x, d = 2) sprintf(paste0("%1.",d,"f"), x) 
  
  # read gis files
  filename <- list.files(path = here::here('code_empirical/data_gis'), full.names = T)
  wsd_subset <- lapply(filename[str_detect(filename, "wsd_subset")], st_read)
  point_subset <- lapply(filename[str_detect(filename, "point_subset")], st_read)
  shape <- lapply(filename[str_detect(filename, "shape")], st_read)
  shape[[1]] <- st_set_crs(shape[[1]], st_crs(wsd_subset[[1]]))

  # read theory file
  dat_sim <- read_csv(here::here('code_theory/result/result_sim2020-11-10.csv'))
  
  n_scenario <- dat_sim %>%
    distinct(n_species,
             mean_env_source,
             sd_env_source,
             rho,
             asymmetry_factor,
             min_optim,
             max_optim,
             sd_env_lon,
             theta,
             K0,
             sd_env,
             spatial_env_cor,
             phi,
             min_niche_width,
             max_niche_width,
             niche_cost,
             p_dispersal,
             min_alpha,
             max_alpha) %>% 
    nrow()

  # for Bayes factor
  source(here::here('code_empirical/analysis_rlm_bf.R'))
  
  # for average predictive comparisons
  source(here::here('code_empirical/analysis_apcomp.R'))
  
  # Hokkaido data
  dat_hkd_site <- read_csv(here::here('code_empirical/data_out/data_hkd_site.csv'))

  # Midwest data
  dat_mw_site <- read_csv(here::here('code_empirical/data_out/data_mw_site.csv')) %>% 
    mutate(Year = format(as.Date(Date, format = '%m/%d/%Y'), "%Y"))

```

**Authors:** Akira Terui^1^, Seoghyun Kim^1^, Christine L. Dolph^2^, Taku Kadoya^3^, Yusuke Miyazaki^4^

**Affiliations:** ^1^ Department of Biology, University of North Carolina at Greensboro, Greensboro, NC 27412, USA ^2^ Department of Ecology, Evolution and Behavior, University of Minnesota, St. Paul, MN 55108, USA ^3^ National Institute for Environmental Studies, Tsukuba, Ibaraki 305-8506, Japan ^4^ Shiraume Gakuen College, Kodaira, Tokyo 187-8570, Japan

**Abstract:** A prevailing paradigm suggests that species richness increases with area in a decelerating way; this ubiquitous power-law scaling, the species-area relationship, has formed the foundation of many conservation strategies. In spatially complex ecosystems, however, the area may not be the sole dimension to scale biodiversity patterns because the scale-invariant complexity of fractal ecosystem structure may drive ecological dynamics in space. Here, we use theory and analysis of extensive fish community data from two distinct geographic regions to show that riverine biodiversity follows a robust scaling law along the two orthogonal dimensions of ecosystem size and complexity (i.e., the dual scaling law). In river networks, the recurrent merging of various tributaries forms fractal branching systems, where the prevalence of branching (ecosystem complexity) represents a macro-scale control of the ecosystem's habitat heterogeneity. In the meantime, ecosystem size dictates metacommunity size and total habitat diversity, two factors regulating biodiversity in nature. Our theory predicted that, regardless of simulated species' traits, larger and more branched 'complex' networks support greater species richness due to increased space and environmental heterogeneity. The relationships were linear on logarithmic axes, indicating power law scaling by ecosystem size and complexity. In support of this theoretical prediction, the power laws have consistently emerged in riverine fish communities across the study regions (Hokkaido Island in Japan and the Midwestern United States) despite hosting different fauna with distinct evolutionary histories. The emergence of dual scaling law may be a pervasive property of branching networks with important implications for biodiversity conservation.

**Significance** Larger ecosystems support more species; this ubiquitous pattern is the foundation of current conservation schemes. However, many ecosystems possess a complex spatial structure that cannot be represented by area, and the role of such complexity in scaling biodiversity patterns is largely unknown. Here, we use theory and extensive fish community data to show that ecosystem size and complexity dictate riverine biodiversity. We found that larger and more branched 'complex' river networks harbored greater species richness due to increased space and environmental heterogeneity. The complexity effect was comparable to the size effect, and this pattern has emerged regardless of ecological contexts. The dual scaling of biodiversity may be a pervasive feature that has far-reaching implications for biodiversity conservation.

**Key words:** metacommunity, species diversity, scaling law, network theory, freshwater

## Introduction

Ecologists have long sought to understand the general drivers of biodiversity. One of the most robust empirical generalizations in ecology is the positive relationship between species richness and area, i.e., the species-area relationship (the SAR) [@lomolinoEcologyMostGeneral2000]. In 1921, Arrhenius @arrheniusSpeciesArea1921 formulated the SAR as a power law $S = cA^z$, an equation currently known as the Arrhenius species-area relationship ($S$ is the number of species observed in a given geographic area $A$, $c$ the constant, and $z$ the scaling exponent). Since then, the spatial scaling of species richness has been observed in many taxonomic groups [@triantisIslandSpeciesareaRelationship2012]. The SAR is ubiquitous because multiple mechanisms produce an apparently similar pattern. Larger ecosystems typically support more diverse metacommunities due to increased habitat diversity [@kallimanisHowDoesHabitat2008], larger metacommunity size [@hubbellUnifiedNeutralTheory2001], and/or enhanced colonization dynamics [@lososTheoryIslandBiogeography2009]. Importantly, the SAR provides the foundation for global conservation efforts [@neigelSpeciesareaRelationshipsMarine2003; @desmetUsingSpeciesareaRelationship2004; @myersBiodiversityHotspotsConservation2000]. For example, conservation ecologists have used SAR estimates to design marine and terrestrial protected areas [@neigelSpeciesareaRelationshipsMarine2003; @desmetUsingSpeciesareaRelationship2004], which currently encompass more than 30 million km^2^ globally [@deguignet2014UnitedNations2014].

Many ecosystems, however, possess a complex spatial structure that cannot be represented by area - a dimension referred to as scale-invariant complexity [@turnerLandscapeEcologyTheory2015; @rodriguez-iturbeFractalRiverBasins2001]. Such complexity is evident in branching ecosystems, including rivers, trees, and mountain ranges, to name just a few [@rodriguez-iturbeFractalRiverBasins2001]. Geomorphic or biological processes generate a pronounced self-similarity in complex branching patterns such that the part and the whole look alike [@rodriguez-iturbeFractalRiverBasins2001]. Even though the branching structure is independent of spatial scale, it forms a physical template that dictates habitat diversity and dispersal corridors for living organisms [@grantLivingBranchesPopulation2007]. Limited, but accumulating evidence suggests that classical metapopulation and metacommunity theories cannot predict ecological dynamics driven by branching structure [@faganConnectivityFragmentationExtinction2002; @grantUseMultipleDispersal2010; @brownDendriticNetworkStructure2010], and this recognition has led to recent developments of spatial theories devoted to complex branching ecosystems [@rinaldoRiverNetworksEcological2018]. For example, these studies have highlighted key roles of branching structure in driving local biodiversity patterns, such as increased species richness at merging points of branches [@carraraDendriticConnectivityControls2012]. However, most empirical research has explored the consequences of branching complexity for local community structure [@erosLandscapeEcologyRivers2019] or has relied solely on theoretical arguments with limited replications of branching architecture [@holtRoleBranchingMaintenance2018]. At present, we lack a comprehensive evaluation of how branching complexity scales biodiversity patterns at the metacommunity level. Filling this knowledge gap may provide common ground for achieving successful conservation in spatially complex ecosystems, where accelerated species loss threatens the delivery of ecosystem services [@reidEmergingThreatsPersistent2019].

Here, we propose a unified framework of ecosystem size and complexity in scaling biodiversity patterns in rivers - a prime example of complex branching ecosystems. Individual streams and rivers flow through different landscapes with distinct geological and climatic backgrounds, serving as a spatial unit of unique in-stream environments [@brownDendriticNetworkStructure2010; @petersonModellingDendriticEcological2013; @mooreEmergentStabilityLarge2015; @teruiMetapopulationStabilityBranching2018; @isaakSlowClimateVelocities2016; @mcguireNetworkAnalysisReveals2014; @abbottUnexpectedSpatialStability2018]. The recurrent merging of diverse tributaries ultimately forms a fluvial network with fractal branching patterns [@rodriguez-iturbeFractalRiverBasins2001]. As such, the complexity of branching structure, which we define here as the probability of branching per unit river distance [@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014], may represent a macro-scale control of the ecosystem's habitat heterogeneity (habitat diversity per unit area) [@grantLivingBranchesPopulation2007; @mooreEmergentStabilityLarge2015; @teruiMetapopulationStabilityBranching2018]. Meanwhile, ecosystem size (watershed area) should determine the metacommunity size and total habitat diversity (area times heterogeneity), two factors that regulate biodiversity at the metacommunity level [@hubbellUnifiedNeutralTheory2001; @kallimanisHowDoesHabitat2008]. Hence, riverine biodiversity may manifest scaling laws along the two orthogonal dimensions of branching networks. We call this the dual scaling hypothesis of biodiversity.

The present study combines theory and analysis of extensive community data from two different regions of the globe to show that multiple ecological pathways converge to the emergence of dual diversity scaling. Specifically, watershed-scale species richness ($\gamma$ diversity) followed power laws with ecosystem size $A$ and branching probability $P_b$ as $\gamma = cA^{\xi_1}P_b^{\xi_2}$ ($\xi_1$ and $\xi_2$ are the scaling exponents) regardless of ecological contexts. However, contributing factors of increased $\gamma$ diversity - either enhanced local species richness ($\alpha$ diversity) and/or spatial variation of species composition ($\beta$ diversity) - depended on constituent species' characteristics. Our findings suggest that the dual scaling law is a pervasive yet overlooked feature of complex ecosystems with important implications for biodiversity conservation.

## Results and Discussion

### Theoretical synthesis of ecosystem size and complexity influences

We developed a theoretical framework synthesizing the influences of ecosystem size and complexity on biodiversity patterns in branching ecosystems. We depicted branching ecosystems as a spatial network of connected habitat patches which local communities inhabit [@yeakelSynchronisationStabilityRiver2014; @teruiMetapopulationStabilityBranching2018] (**Figure 1A and B**). Two factors determine the mean environmental condition at each habitat patch $\mu_z$: (1) headwater environments (the most upstream habitat patch) and (2) local environmental noise. Environmental values at headwaters are drawn randomly from a normal distribution with a mean of zero and a standard deviation of $\sigma_h$ and propagate downstream. We modeled the downstream propagation as a spatial autoregressive process, in which local noise is added to the adjacent upstream environment as $\mu_{z,k} \sim Normal(\mu_{z,k+1}, \sigma_{l}^2)$ ($k$ is the network distance from the outlet patch; $k = 1$ at the outlet) . The environmental values recurrently 'mix' at confluences considering the relative size of joining tributaries (see **Materials and Methods**). Therefore, our network-generation procedure resembles natural processes of how branching river networks create diverse habitats in a metacommunity [@mcguireNetworkAnalysisReveals2014].

Metacommunity dynamics were then simulated in the theoretical branching networks using a general metacommunity model [@thompsonProcessbasedMetacommunityFramework2020]. In this model, the realized species' population growth is regulated by local abiotic environments, competition, and dispersal. Specifically, the number of individuals $N_{ix}(t + 1)$ for species $i$ at patch $x$ and time $t+1$ was given as:

$$
N_{ix}(t + 1) \sim Poisson(n_{ix}(t) + I_{ix}(t) - E_{ix}(t))
$$

where $n_{ix}(t)$ is the expected number of individuals given the local community dynamics at time $t$, $I_{ix}(t)$ the expected number of immigrants to patch $x$, and $E_{ix}(t)$ the expected number of emigrants from patch $x$. We assumed the Beverton-Holt equation to simulate local community dynamics [@bevertonDynamicsExploitedFish1957]:

$$
\begin{aligned}
n_{ix}(t) = \frac{N_{ix}(t)r_{ix}(t)}{1 + \frac{r_{0,i}-1}{K_{x}}\sum_{j=1}^S{b_{ij}N_{jx}(t)}}
\end{aligned}
$$

$r_{ix}(t)$ is the site- and time-specific reproductive rate of species $i$, $r_{0,i}$ the maximum reproductive rate, $K_{x}$ the site-specific carrying capacity, $b_{ij}$ the competition coefficient between species $i$ and $j$, and $S$ the number of species in a metacommunity ($S = 50$). Interspecific competition coefficients are random draws from a uniform distribution as $b_{ij, i \neq j} \sim Unif(0,b_{max})$ while keeping intraspecific competition coefficients constant ($b_{ii} = 1$). Here, the reproductive rate $r_{ix}(t)$ was related to local abiotic environments through a Gaussian function with species' niche optimum $\mu_i$ and width $\sigma_{niche,i}$. That is, $r_{ix}(t)$ decreases as temporally-variable abiotic environments (drawn randomly from the mean environment $\mu_{z,x}$) deviate from $\mu_i$ (see **Materials and Methods**). Species' reproductive performance has therefore an explicit linkage with local abiotic environments, which can be driven largely by branching structure. After local community dynamics, species emigrate from the local habitat patch with probability $p_d$ and disperse through the branching network following an exponential dispersal kernel with the rate parameter $\theta$ (the reciprocal $1/\theta$ represents an expected dispersal distance). These dispersal parameters affect the number of immigrants $I_{ix}(t)$ and emigrants $E_{ix}(t)$.

Prior to the main simulation analysis, we performed a systematic sensitivity analysis to identify simulation parameters that strongly influence the relationships between biodiversity metrics ($\alpha$, $\beta$, and $\gamma$ diversity) and ecosystem properties (size and complexity). Our analysis revealed that the following parameters were particularly influential: environmental variation at headwaters $\sigma_h$, local environmental noise $\sigma_l$, maximum value of interspecific competition coefficient $b_{max}$ , dispersal probability $p_d$, and dispersal rate parameter $\theta$ (**Supporting Information**). Therefore, we considered `r n_scenario` combinations of these parameters as primary simulation scenarios, which include a combination of four landscape and eight ecological scenarios.

The four landscape scenarios represent distinct patterns of spatial environmental heterogeneity, which were produced by different combinations of environmental variation at headwaters ($\sigma_h =$ `r unique(dat_sim$sd_env_source)`) and the degree of local environmental noise ($\sigma_l =$ `r unique(dat_sim$sd_env_lon)`). When $\sigma_h > \sigma_l$, branching produces greater habitat heterogeneity because headwaters are the primary source of environmental variation (**Figure 1A**). This landscape scenario reproduces natural patterns of habitat heterogeneity, in which environmental conditions differ greatly among tributaries but are highly correlated within a tributary [@petersonModellingDendriticEcological2013; @mcguireNetworkAnalysisReveals2014]. In the meantime, when $\sigma_h \le \sigma_l$, local environmental noise masks environmental variation among tributaries, leading to limited influences of branching on habitat heterogeneity (**Figure 1B**). This scenario may reflect human-modified landscapes, in which human activities may reduce the headwater diversity $\sigma_h$ by homogenizing in-stream processes (e.g., dams) [@poffHomogenizationRegionalRiver2007] and/or may increase the local environmental noise $\sigma_l$ through localized habitat degradation (e.g., removal of riparian forests) [@dala-corteThresholdsFreshwaterBiodiversity2020]. Thus, the inequality between $\sigma_h$ and $\sigma_l$ defines the contrasting scenarios of natural and human-dominated landscapes. The eight ecological scenarios distinguish ecological characteristics of constituent species in a metacommunity. Among the ecological scenarios, we changed dispersal distance ($\theta = 0.1, 1.0$), dispersal probability ($p_{d} = 0.01, 0.1$), and the maximum value of interspecific competition strength ($b_{max} = 0.75, 1.50$). This setup enables us to examine how ecological traits of constituent species mediate biodiversity relationships. The combinations of landscape and ecological scenarios were capable of reproducing common spatial patterns of local species richness in rivers, corroborating the appropriateness of our choice in parameter combinations (**Supporting Information**). Under each simulation scenario, we simulated 1400 time steps of metacommunity dynamics (including 400 time steps of initialization and burn-in periods) in `r max(dat_sim$n_rep)` branching networks with the gradients of ecosystem size (the number of habitat patches: `r min(dat_sim$n_patch)` to `r max(dat_sim$n_patch)`) and complexity (branching probability: `r round(min(dat_sim$p_branch), 2)` to `r round(max(dat_sim$p_branch), 2)`).

Our simulation predicted the emergence of dual scaling law under a realistic landscape scenario, where the environmental variation at headwaters $\sigma_h$ is greater than the degree of local environmental noise $\sigma_l$ (**Figure 1A**). Ecosystem size and complexity both increased $\gamma$ diversity (**Figures 2A and 3A**) with a signature of power law (i.e., linear in a log-log scale), and these relationships were consistent across ecological scenarios (compare panels in **Figures 2A and 3A**). Importantly, the impact of ecosystem complexity was comparable to that of ecosystem size. Hence, regardless of ecological scenarios, ecosystem size and complexity are likely to be equally important in scaling $\gamma$ diversity. Our results contrast with predictions from neutral models, in which the enhanced connectivity of highly branched networks reduced $\gamma$ diversity by facilitating the further expansion of an already widespread species [@muneepeerakulEvolvingBiodiversityPatterns2019]. Non-neutral components of our model should therefore have played a central role in generating the predicted patterns. Indeed, the robustness of the scaling law stemmed from the convergence of niche and dispersal assembly as described below.

Dispersal regulated community assembly processes that converged to the robust scaling relationships of $\gamma$ diversity (compare left and right columns in **Figures 2A and 3A**). We observed a greater contribution of $\beta$ diversity (defined as $\frac{\gamma}{\alpha}$) to increased $\gamma$ diversity when dispersal limitation existed (i.e., species travel short distances). This result reflected significant spatial variation in species composition over the branching network and was likely driven by the local association of species' niche and abiotic environments (i.e., species sorting) [@leiboldMetacommunityConceptFramework2004; @thompsonProcessbasedMetacommunityFramework2020]. In contrast, when the dispersal limitation was relaxed (species travel long distances), a clear increase in $\alpha$ diversity underpinned the positive relationships between $\gamma$ diversity and ecosystem properties. The results agree with previous predictions that increased dispersal homogenizes community composition while enhancing local diversity through increased immigrants from suitable habitat patches (i.e., mass effects) [@leiboldMetacommunityConceptFramework2004; @economoSpeciesDiversityNeutral2008; @thompsonProcessbasedMetacommunityFramework2020]. Therefore, ecosystem size and complexity can increase $\gamma$ diversity via enhanced species sorting or mass effects, and which takes primacy is dependent on the degree of dispersal limitation. These patterns were qualitatively similar across different levels of dispersal probabilities (**Figures S5 and S12**).

Interspecific competition had minimal influences on the underlying mechanisms (compare top and bottom rows in **Figures 2A and 3A**). Strong competition reduced $\alpha$ diversity as observed in former studies [@thompsonProcessbasedMetacommunityFramework2020]. Yet, it did not change the qualitative relationships between biodiversity and ecosystem properties (**Figures 2A and 3A**). Accordingly, macroecological patterns are expected to be robust to variation in species interaction networks. This result deserves attention given the long-lasting debate on how species interactions change the dynamics of ecological communities [@kadoyaPotentialOscillatorsKeystone2018; @ushioFluctuatingInteractionNetwork2018]. Collectively, our theoretical analysis highlights how apparently similar scaling in $\gamma$ diversity emerges through different ecological pathways by explicitly modeling niche and dispersal assembly processes.

It should be borne in mind that influences of ecosystem size and complexity differed significantly in their dependence on landscape scenarios. Ecosystem size had positive effects on $\gamma$ diversity regardless of landscape scenarios, although the slopes were steeper with greater environmental variation (higher $\sigma_h$ and/or $\sigma_l$) (**Figures 2A and S5-S11**). This result is attributable to the fact that larger ecosystems can hold more individuals in a metacommunity [@hubbellUnifiedNeutralTheory2001]. In contrast, we observed limited or no influences of branching complexity when local environmental noise was equal to or exceeded environmental variation at headwaters ($\sigma_h \le \sigma_l$; **Figures S13-S18**). Under this scenario, branching has a minor influence on the ecosystem's habitat heterogeneity because patch-level environmental variation is equivalent to or greater than environmental differences between tributaries (**Figure 1B**). Therefore, this landscape scenario eliminates the positive effect of branching complexity on $\gamma$ diversity. This theoretical prediction may not apply to pristine or semi-natural river networks where individual streams show distinct and spatially-correlated environmental conditions, including water temperature, water chemistry, and flow/sediment regimes [@petersonModellingDendriticEcological2013; @mooreEmergentStabilityLarge2015; @mcguireNetworkAnalysisReveals2014]. Instead, it may be most relevant to severely altered landscapes where human disturbance disrupts the environmental distinctiveness of branches through, for example, flow regulations by dams [@poffHomogenizationRegionalRiver2007]. Hence, our theory has important implications for riverine biodiversity conservation by pointing to the crucial role of habitat diversity produced by branching structure.

### Empirical evidence from distinct geographic regions

The proposed theory provided important insights into how ecological communities are structured in branching networks; however, empirically testing the predictions is extremely difficult because it requires metacommunity-level replications. To confront this logistical challenge, we compiled fish community data across two geographic regions: Hokkaido Island in Japan and the Midwestern US (Midwest). These regions are located in comparable latitude ranges (**Figure 1D**) but support distinct fish communities (**Tables S5 and S6**). Therefore, this data set provides an excellent opportunity to examine the generality of our theoretical predictions. After careful data selection (see **Materials and Methods** and **Supporting Information**), we estimated $\alpha$, $\beta$, and $\gamma$ diversity (asymptotic species richness; **Materials and Methods**) at `r nrow(wsd_subset[[1]]) + nrow(wsd_subset[[2]])` watersheds (`r nrow(wsd_subset[[1]])` in Hokkaido and `r nrow(wsd_subset[[2]])` in the Midwest), each of which comprised $\ge$ 10 sites of presence-absence fish community data (a total of `r nrow(point_subset[[1]]) + nrow(point_subset[[2]])` sites). These watersheds are small enough (`r round(min(c(wsd_subset[[1]]$area, wsd_subset[[2]]$area)))` to `r round(max(c(wsd_subset[[1]]$area, wsd_subset[[2]]$area)))` km^2^) to assume that fishes can disperse therein at a multi-generation time scale [@comteFishDispersalFlowing2018], while posing challenges to traverse across watersheds (the ocean or lentic habitats; see **Materials and Methods** for watershed definition). We combined this data set with geospatial information, including watershed characteristics (watershed area and branching probability), climates (annual mean temperature and annual cumulative precipitation), and land use patterns (the fraction of agricultural land use and dam density) to evaluate potential influences of macro-scale factors.

Using this data set, we were able to ask the following questions that have never been addressed in tandem: Is there a dual scaling law in riverine biodiversity? If so, is the dual scaling consistent across different geographic regions despite hosting drastically different fauna with distinct evolutionary histories? To test these questions, we developed global and region-specific models of robust linear regression in log-log space (see **Materials and Methods**). In the global model, we assumed that slopes of ecosystem size (watershed area) and complexity (branching probability) are constant across the two regions (i.e., fixed scaling exponents). Meanwhile, the region-specific model assumes different slopes of ecosystem size and complexity between the regions (i.e., varied scaling exponents). We compared the support of these competing models using the Bayes factor, a measure of the strength of evidence in favor of one model over the alternative. In our definition (**Materials and Methods**), the Bayes factor of $> 1$ indicates the support for the global model over the region-specific model.

Surprisingly, we found decisive support for the global model in explaining $\gamma$ diversity (Bayes factor = `r round(fit$gamma$bayes_factor, 1)`). The estimated $\gamma$ diversity linearly increased with increasing watershed area (ecosystem size) and branching probability (ecosystem complexity) on a log-log scale, and the estimated scaling exponents were consistent across the study regions (`r op(coef(fit$gamma$model)[2])` for watershed area and `r op(coef(fit$gamma$model)[3])` for branching probability; **Table 1 and Figures 2B and 3B**). Thus, watershed-scale riverine biodiversity likely obeys a general scaling law along the two independent axes of ecosystem size and complexity. The regional consistency implies that ecological traits of constituent species have a minor effect on the scaling relationships, as our theory predicts (**Figures 2A and 3A**). It is also important to note that the effect of ecosystem complexity was striking in its magnitude. Average predictive comparisons [@gelmanAveragePredictiveComparisons2007] revealed that an expected increase of $\gamma$ diversity per 0.1 branching probability was `r op(ap_est$sim_estimate[2] * 0.1)` $\pm$ `r op(ap_est$sim_se[2] * 0.1)` species (**Materials and Methods** and **Supporting Information**); this level of increase in $\gamma$ diversity requires `r round(ap_est$sim_estimate[2] * 0.1 / ap_est$sim_estimate[1])` km^2^ in the watershed area (see **Table S7** for the estimated average predictive comparisons). Overall, the observed patterns were reasonable because numerous studies have shown that tributaries are the primary source of environmental heterogeneity in river networks [@brownDendriticNetworkStructure2010; @petersonModellingDendriticEcological2013; @mooreEmergentStabilityLarge2015; @teruiMetapopulationStabilityBranching2018; @isaakSlowClimateVelocities2016; @mcguireNetworkAnalysisReveals2014; @abbottUnexpectedSpatialStability2018] - the sole theoretical assumption required for the dual scaling of $\gamma$ diversity to emerge.

Similarly, there were weak to moderate supports for the global models of $\alpha$ and $\beta$ diversity (Bayes factor = `r round(fit$alpha$bayes_factor, 1)` and `r round(fit$beta$bayes_factor, 1)`, respectively). In both regions, $\beta$ diversity responded significantly to ecosystem size and complexity while $\alpha$ diversity showing a weaker or a vague response to these ecosystem properties (**Table 1 and Figures 2B and 3B**). In our simulations, this pattern has emerged under the scenarios with dispersal limitation, which elegantly matches the previous observations of stream fish movement. Field studies (e.g., mark-recapture) recurrently revealed the restricted movement of stream fish, typically limited to several hundreds of meters at an annual time scale [@radingerPatternsPredictorsFish2014]. The reciprocal agreement of theoretical and empirical patterns provides indirect but convincing evidence that dispersal limitation, which results in the increasing importance of species sorting process (**Figures 2 and 3**), plays a key role in driving the associations between $\gamma$ diversity and ecosystem properties in rivers.

The consistent effect of branching probability on $\gamma$ diversity across the study regions is noteworthy because many watersheds in the Midwest have been altered by agricultural land use (mean % agricultural land use: `r round(mean(wsd_subset[[2]]$frac_agri)*100)`% in the Midwest and `r round(mean(wsd_subset[[1]]$frac_agri)*100)`% in Hokkaido). If the intensive land use by humans impairs biological or physical distinctiveness among tributaries, theory predicts a weakened effect of branching probability on $\gamma$ diversity (**Figures S13-S18**). However, $\gamma$ diversity increased significantly with increasing branching probability in this highly modified landscape, suggesting that tributaries still sustain unique environmental conditions to support high spatial variation in species composition. Indeed, $\beta$ diversity increased with increasing branching probability in both regions (**Figure 4**). It is conceivable that local geological and geomorphological differences, such as slope, aspect, and soil porosity, persist in human-dominated landscapes to maintain the diversity of in-stream processes. The lack of land use effects (the fraction of agricultural land use and dam density) further corroborates our interpretation (**Table 1**). Although our analysis is correlative, the finding is encouraging because the branching complexity of river networks may serve as a natural defense system to human-induced environmental changes.

A potential criticism is that our results are driven by spurious correlations; however, this is very unlikely. We have statistically controlled the potential influences of climates and land use patterns (**Table 1**). Moreover, our empirical results were qualitatively consistent with theoretical predictions, which are free from any confounding factors. Thus, we are confident in our statistical inference.

### Implications

Recent advancement of spatial theories has sparked discussion of how the complex spatial structure of ecosystems drives macroecological patterns of diverse organisms. Several studies have explicitly considered the physical architecture of branching networks [@rinaldoRiverNetworksEcological2018] and have succeeded in reproducing some of the core biodiversity patterns (e.g., spatial distribution of local species richness) at coarse spatial resolutions (\~5000 km^2^) [@muneepeerakulNeutralMetacommunityModels2008a]. Yet, we have overlooked one of the fundamental rules in complex ecosystems, i.e., the dual scaling law. Here, the unified framework of ecosystem size and complexity provided strong evidence for the dual scaling law. Notably, this pattern has emerged irrespective of ecological contexts or geographic regions, emphasizing the generality of our findings. The dual scaling law of biodiversity may be an overlooked yet pervasive property of branching ecosystems.

In particular, the emerging complexity-diversity relationship points to several important avenues for riverine biodiversity conservation. First and foremost, there is now a clear need to explicitly consider the dimension of ecosystem complexity to achieve successful conservation. Human-induced habitat alterations, including flow regulation [@poffHomogenizationRegionalRiver2007], habitat fragmentation [@grillMappingWorldFreeflowing2019], and stream burial [@elmoreDisappearingHeadwatersPatterns2008], may compromise or restrict access to the diverse habitats that complex branching networks may support. Hence, it is imperative to recognize the role of branching complexity and minimize the homogenizing effects of human activities. Second, the complexity perspective may provide insights into the spatial planning of conservation efforts. Riverine reserves and local restoration are increasingly recognized as an effective management tool, and designing a spatial network of conservation sites in rivers is an area of active research [@koningNetworkGrassrootsReserves2020]. While large reserves or restoration sites are undoubtedly important, our results indicate the potential of coordinated networks of local conservation sites in protecting biodiversity. For example, synergies of multiple small reserves may emerge at the watershed scale when ecologically-distinct tributaries are involved in the design, as evidenced by the recent successful conservation of tropical fishes in Thailand's Salween basin [@koningNetworkGrassrootsReserves2020].

While the prevailing evidence supports the importance of ecosystem size in biodiversity relationships [@hubbellUnifiedNeutralTheory2001; @triantisIslandSpeciesareaRelationship2012; @iwasakiEvaluatingRelationshipBasinscale2012; @saboRoleDischargeVariation2010], ecosystem complexity has not received the attention it deserves. However, the ubiquity of scale-invariant complexity across terrestrial [@turnerLandscapeEcologyTheory2015] and aquatic ecosystems [@rodriguez-iturbeFractalRiverBasins2001] calls for more research embracing the two orthogonal dimensions of the ecosystem's geometric structure. Our fundamental findings should apply beyond branching ecosystems because ecosystem size and complexity both represent a physical 'template' providing a wide spectrum of niche opportunities for living organisms. Further, the proposed framework may be extended to other aspects of biodiversity; for example, a logical next step is to explore how these ecosystem properties regulate functional diversity [@petcheyFunctionalDiversityFD2002; @suHumanImpactsGlobal2021] and shifts in community assembly processes [@chaseStochasticCommunityAssembly2010]. Recognizing the dual scaling of biodiversity broadens viable options for spatial planning of protected areas or restoration sites, thereby helping conserve biodiversity from societal demands that threaten it. The generalization of our findings in spatially complex ecosystems represents a frontier for future research.

\newpage

# Materials and Methods

## Theory

### Network generation

We depicted branching ecosystems as a bifurcating network of connected habitat patches [@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014] (**Figure 1**). Habitat patches, or local communities, can be either non-branching or branching river sections with a unit length $l$, which defines the scale of local species interactions. Two parameters determine the geometric properties of simulated branching networks: the number of habitat patches $N_p$ (ecosystem size) and branching probability $P_b$ (ecosystem complexity). Each habitat patch is assigned to be a branching patch (including upstream terminals) with probability $P_b$ or a non-branching patch with probability $1-P_b$. In this framework, an individual branch is a consecutive series of non-branching patches terminated at a branching patch; therefore, the number of habitat patches in branch $q$, $n_{p,q}$, is a realization of a random variable drawn from a geometric distribution $n_{p,q} \sim Ge(P_{b})$ [@teruiMetapopulationStabilityBranching2018] but conditional on $\sum_{q=1}^{N_b}n_{p,q} = N_p$ ($N_b$ is the number of branches in a network). The number of branches $N_b$ is identical to the number of branching habitat patches in a network, or the number of 'success' out of $N_p$ trials. This leads to an assumption that $N_b$ is a realization of a random variable drawn from a binomial distribution as $N_b \sim Binomial(N_p, P_b)$. This framework has two merits. First, it reflects observed patterns of branch length distribution, which is known to follow an exponential distribution (a continuous version of a geometric distribution) [@rodriguez-iturbeFractalRiverBasins2001]. Second, it preserves the fractal nature of branching patterns [@peckhamReformulationHortonLaws1999]. An alternative approach is the use of optimal channel networks [@carraroGenerationApplicationRiver2020]. However, we employed our framework because branching probability $P_b$ is quantifiable in natural river networks, enabling us to compare theoretical predictions with empirical observations.

In our network generation, we first drew $N_b$ from the binomial distribution but selected an odd number to constitute a bifurcating branching network. We then determined $n_{p,q}$ as random draws from the geometric distribution with the constraint of $\sum_{q=1}^{N_b}n_{p,q} = N_p$. The generated branches were organized randomly into a bifurcating branching network.

Two sources of variation characterize the long-term average of the abiotic environment at each habitat patch: environmental variation at headwaters ($\sigma_h$) and local environmental noise ($\sigma_l$). We drew random values from a normal distribution with a mean of zero and a standard deviation of $\sigma_{h}$ and assigned them to headwater patches (i.e., the most upstream patches). These environmental values at headwaters propagate downstream through a spatial autoregressive process defined as:

$$
\begin{aligned}
\mu_{z,k} = \rho \mu_{z,k+1} + \epsilon_k &\text{(1)}
\end{aligned}
$$

where $\mu_{z,k}$ is the mean environmental value at longitudinal position $k$ ($k$ is the network distance from the outlet patch; $k = 1$ at the outlet), $\rho$ the strength of spatial autocorrelation, and $\epsilon_k$ the local environmental noise that follows a normal distribution with a mean of zero and a standard deviation of $\sigma_l$. The parameter $\rho$ can take values of 0-1 with larger values indicating greater spatial autocorrelation. In this study, we set $\rho = 1$ to mimic strong spatial autocorrelation in riverine environments. At confluences, we took a weighted mean of environmental values given the relative size of upstream contributing area of joining tributaries:

$$
\begin{aligned}
\mu_{z,k} &= \omega(\rho \mu_{z,k+1}^R + \epsilon_{k}^R) + (1-\omega)(\rho \mu_{z,k+1}^L + \epsilon_{k}^L) &&\\
\omega &= \frac{A_{k+1}^R}{A_{k+1}^R + A_{k+1}^L} &&\text{(2)}
\end{aligned}
$$

where $R$ and $L$ denote "right" and "left" branches, respectively, and $A_k$ is the number of upstream habitat patches at longitudinal position $k$ (akin to the upstream watershed area; $A_k = 1$ at the most upstream patch). The parameter $\omega$ takes values of 0-1 and represents the relative influence of the right tributary given the relative size of joining tributaries. With this expression, larger tributaries have a greater influence on the downstream environment, as observed in natural river networks [@bendaNetworkDynamicsHypothesis2004].

### Metacommunity model

We simulated metacommunity dynamics in branching river networks following the metacommunity framework proposed by Thompson et al [@thompsonProcessbasedMetacommunityFramework2020]. In this framework, abiotic environmental conditions (density-independent), intra- and interspecific competition (density-dependent), and dispersal regulate a species' realized population growth. Below, we describe the details of our metacommunity model.

The realized number of individuals $N_{ix}(t + 1)$ (species $i$ at patch $x$ and time $t+1$) is given as:

$$
\begin{aligned}
N_{ix}(t + 1) \sim Poisson(n_{ix}(t) + I_{ix}(t) - E_{ix}(t)) &\text{(3)}
\end{aligned}
$$

where $n_{ix}(t)$ is the expected number of individuals given the local community dynamics at time $t$, $I_{ix}(t)$ the expected number of immigrants to patch $x$, and $E_{ix}(t)$ the expected number of emigrants from patch $x$. The realized discrete number of individuals is drawn from a Poisson distribution to account for stochasticity in demographic and dispersal processes [@fronhoferClassicalMetapopulationDynamics2017; @thompsonProcessbasedMetacommunityFramework2020]. Local community dynamics are simulated based on the Beverton-Holt equation [@bevertonDynamicsExploitedFish1957]:

$$
\begin{aligned}
n_{ix}(t) = \frac{N_{ix}(t)r_{ix}(t)}{1 + \frac{r_{0,i}-1}{K_{x}}\sum_{j=1}^S{b_{ij}N_{jx}(t)}} &\text{(4)}
\end{aligned}
$$

where $r_{ix}(t)$ is the reproductive rate of species $i$ given the environmental condition at patch $x$ and time $t$, $r_{0,i}$ the maximum reproductive rate of species $i$, $K_{x}$ the carrying capacity at patch $x$, $b_{ij}$ the competition coefficient between species $i$ and $j$, and $S$ the number of species in a metacommunity. $K_x$ was expressed as a function of the number of upstream habitat patches $A_x$ ($K_x = 100A_x$) to represent increasing habitat size with increasing upstream watershed area [@teruiThreeEcologicalFactors2016; @rahelFishAssemblagesHabitat1991]. The parameter $b_{ij}$ represents the strength of interspecific competition relative to that of intraspecific competition: interspecific competition is greater than intraspecific competition if $b_{ij}$ \> 1 (intraspecific competition coefficient was set constant as $b_{ii} = 1$). $b_{ij}$ was drawn randomly from a uniform distribution as $b_{ij} \sim Unif(0, b_{max})$. The density-independent reproductive rate $r_{ix}(t)$ is affected by abiotic environments (non-consumable) and determined by the following Gaussian function:

$$
\begin{aligned}
r_{ix}(t) = \delta~r_{0,i}~exp[{-\frac{\{\mu_i-z_x(t)\}^2}{2\sigma^2_{niche,i}}}] &\text{(5)}
\end{aligned}
$$

where $\mu_i$ is the optimal environmental value for species $i$, $z_x(t)$ the environmental value at patch $x$ and time $t$, and $\sigma_{niche,i}$ the niche width of species $i$. We introduced the cost of a wide niche by multiplying $\delta$ [@chaianunpornEvolutionaryResponsesClimate2015]:

$$
\begin{aligned}
\delta = exp(-\frac{\sigma_{niche,i}^2}{2\nu^2}) &\text{(6)}
\end{aligned}
$$

Smaller values of $\nu$ imply greater costs of having a wider niche (i.e., decreased maximum reproductive rate) and reduce the realized reproductive rate $r_{ix}(t)$ near the niche optimum.

The environmental value at patch $x$ and time $t$, $z_x(t)$, is assumed to follow a multivariate normal distribution as $z_{x}(t) \sim MVN(\boldsymbol{\mu_z}, \boldsymbol{\Omega_z})$, where $\boldsymbol{\mu_z}$ is the vector of mean environmental conditions of habitat patches and $\boldsymbol{\Omega_z}$ is the variance-covariance matrix. The diagonal elements of the variance-covariance matrix $\sigma^2_z$ represent the degree of temporal environmental variation. The off-diagonal elements $\Omega_{xy}$ represent the spatial autocorrelation in temporal environmental variation as:

$$
\begin{aligned}
\Omega_{xy} = \sigma_z^2~exp(-\phi d_{xy}) &\text{(7)}
\end{aligned}
$$

$\Omega_{xy}$ denotes the temporal covariance of environmental conditions between patch $x$ and $y$, which is assumed to decay exponentially with increasing distance between the patches $d_{xy}$ (the shortest network path measured as the number of habitat patches). The parameter $\phi$ determines the degree of the distance decay of environmental correlates.

The expected number of emigrants at time $t$ is the product of dispersal probability $p_d$ and $n_{ix}(t)$: $E_{ix}(t) = p_{d}n_{ix}(t)$. The immigration probability at patch $x$ for species $i$, $\xi_{ix}(t)$, is calculated using the following equation that accounts for separation distance among habitat patches and dispersal capability of a species:

$$
\begin{aligned}
\xi_{ix}(t) = \frac{\sum_{y,y \neq x}E_{iy}(t)~exp(-\theta d_{xy})}{\sum_{x} \sum_{y,y \neq x}E_{iy}(t)~exp(-\theta d_{xy})} &\text{(8)}
\end{aligned}
$$

The parameter $\theta$ regulates the dispersal distance of a species that follows an exponential distribution ($\theta^{-1}$ corresponds to the expected dispersal distance). The expected number of immigrants is calculated as $I_{ix}(t) = \xi_{ix}(t)\sum_x^{N_p} E_{ix}$.

### Simulation

We used `r n_scenario` sets of parameter combinations (i.e., simulation scenarios) based on the results of extensive sensitivity analysis (**Supporting Information**). The parameter combinations comprises four landscape and eight ecological scenarios. Landscape scenarios distinguish spatial patterns of habitat heterogeneity, while ecological scenarios change ecological traits of simulated species. For landscape scenarios, we used four combinations of environmental variation at headwaters ($\sigma_h = 0.01, 1$) and the degree of local environmental noise ($\sigma_l = 0.01, 1$). The inequality of $\sigma_h$ and $\sigma_l$ controls the relationship between branching complexity and habitat heterogeneity (**Figure 1A and B**). For ecological scenarios, we varied three ecological parameters that are relevant for dispersal and interspecific competition: dispersal distance ($\theta =$ `r unique(dat_sim$theta)`), dispersal probability ($p_d =$ `r unique(dat_sim$p_dispersal)`), and the maximum value of competition coefficients ($b_{max} =$ `r unique(dat_sim$max_alpha)`). This setup results in eight ecological scenarios with different levels of dispersal and competition.

We allowed interspecific variation in niche optimum and width, which were drawn from uniform distributions as $\mu_i \sim Unif(-1, 1)$ and $\sigma_{niche,i} \sim Unif(0.1, 1)$. We used fixed values for the following parameters: maximum reproductive rate ($r_{0,i} =$ 4), niche cost ($\nu =$ `r unique(dat_sim$niche_cost)`), the degree of temporal environmental variation ($\sigma_z =$ `r unique(dat_sim$sd_env)`), and the extent of spatial autocorrelation in temporal environmental dynamics ($\phi =$ `r unique(dat_sim$phi)`).

Under each simulation scenario, we introduced 50 species ($S = 50$) and simulated 1400 time steps of metacommunity dynamics (including 200 time steps for initialization and 200 time steps for burn-in) in `r max(dat_sim$n_rep)` branching networks with the gradients of ecosystem size (the number of habitat patches: `r min(dat_sim$n_patch)` to `r max(dat_sim$n_patch)`) and complexity (branching probability: `r round(min(dat_sim$p_branch), 2)` to `r round(max(dat_sim$p_branch), 2)`). During the first 200 time steps (an initialization period), we initialized the simulation by seeding each habitat patch with populations of each species drawn from a Poisson distribution with a mean of 0.5. We repeated the seeding every 10 time steps during the initialization to allow species to establish their populations if they can grow from low abundances. After the initialization period, we ran 200 time steps as a burn-in period with no seeding to minimize influences of initial conditions. We saved the last 1000 time steps to estimate the temporal averages of $\alpha$, $\beta$, and $\gamma$ diversity. $\beta$ diversity was defined as $\gamma/\alpha$. We removed simulation replicates in which no species established populations over the initial 400 time steps (`r sum(dat_sim$alpha_div == 0)` replicates out of `r nrow(dat_sim)` replicates). Ecosystem size and complexity were drawn randomly from uniform distributions as: $N_p \sim Unif(10, 150)$ and $P_b \sim Unif(0.01, 0.99)$ ($N_p$ was rounded to the nearest integer before running simulations). Values of simulation parameters were summarized in **Table S2**. We performed simulations using R version 4.1.0 [@rcoreteamLanguageEnvironmentStatistical2020].

## Empirical data

### Fish community data

We compiled fish data at two geographic regions: Hokkaido Island in Japan and the Midwestern US (Midwest). For Hokkaido, we used data from the Hokkaido Freshwater Fish Database HFish [@fukushimaModellingEffectsDams2007; @fukushimaHokkaidoFreshwaterFish2011], monitoring data at protected watersheds [@comteRivFishTIMEGlobalDatabase2021; @teruiMetapopulationStabilityBranching2018], and primary data collected by the authors [@miyazakiTemporalDynamicsFluvial2016; @teruiThreeEcologicalFactors2016], which collectively cover the entire island. For the Midwest, we assembled fish community data collected by the Iowa Department of Natural Resources [@iowadepartmentofnaturalresourcesBiologicalAssessmentIowa2004], Illinois Environmental Protection Agency and Illinois Department of Natural Resources [@illinoisenvironmentalprotectionagencyIllinoisWaterMonitoring2014], Minnesota Pollution Control Agency [@minnesotapollutioncontrolagencyDevelopmentFishbasedIndex2014], and Wisconsin Department of Natural Resources [@wisconsindepartmentofnaturalresourcesGuidelinesAssessingFish2018]. We detailed procedures for initial data selection in **Supporting Information**.

We considered watersheds as independent replicates of metacommunities if the river network flows into one of the following: the ocean, a large lake/reservoir ($\ge$ 10 km in the areal area) or a large river that may represent lentic habitats ($\ge$ 5000 km in the watershed area). We estimated $\alpha$, $\beta$, and $\gamma$ diversity at each watershed. $\gamma$ diversity is the total species richness at each watershed. Since it is impossible to sample all species present in each watershed, we used asymptotic species richness as a proxy for $\gamma$ diversity. Asymptotic species richness can be interpreted as the estimated true species richness in a given area when estimated using spatial replicates of local community data within a metacommunity [@chaoRarefactionExtrapolationHill2014a]. We estimated asymptotic species richness using sampling sites located in the same watershed (i.e., spatial replicates within a metacommunity) via the R package 'iNEXT' [@hsiehINEXTPackageRarefaction2016]. Metacommunities with $\ge$ 10 sampling sites were used in our analysis because a small sample size inflates statistical uncertainties in estimating asymptotic species richness (**Supporting Information**). We assessed the completeness of the observed species richness based on sample coverage, which is the total proportional abundances of observed species to the whole metacommunity [@chaoRarefactionExtrapolationHill2014a]. We excluded watersheds whose sample coverage was below 0.9 because the estimates of asymptotic species richness may contain non-negligible statistical uncertainty. $\alpha$ diversity was estimated by taking an average of local species richness at each site. $\beta$ diversity was estimated by dividing the estimated $\gamma$ diversity by $\alpha$ diversity [@whittakerVegetationSiskiyouMountains1960].

After the data selection procedure, we obtained diversity estimates from `r nrow(wsd_subset[[1]]) + nrow(wsd_subset[[2]])` watersheds (Hokkaido: `r nrow(wsd_subset[[1]])`, Midwest: `r nrow(wsd_subset[[2]])`), which encompassed a total of `r nrow(point_subset[[1]]) + nrow(point_subset[[2]])` sites (Hokkaido: `r nrow(point_subset[[1]])`, Midwest: `r nrow(point_subset[[2]])`). Observations ranged from `r min(dat_hkd_site$Year, na.rm = T)` to `r max(dat_hkd_site$Year, na.rm = T)` in Hokkaido and from `r min(dat_mw_site$Year, na.rm = T)` to `r max(dat_mw_site$Year, na.rm = T)` in the Midwest. Fish species observed in the final data set were listed in **Tables S5 and S6**.

### Environmental data

We collected data for watershed characteristics (watershed area [km^2^], branching probability, and mean elevation [m]), climatic variables (mean annual air temperature [degree Celsius] and cumulative precipitation [mm]), and land use (the fractions of forest, urban, and agriculture, and dam density per watershed area [km^-2^]). We used Hydrologically Adjusted Elevations of MERIT Hydro [@yamazakiMERITHydroHighResolution2019] to delineate watershed polygons and river lines (defined as $\ge$ 1 km^2^ in the watershed area), which were separated by either the ocean, large lakes/reservoirs ($\ge$ 10 km^2^ in the areal area), or large rivers ($\ge$ 5000 km^2^ in the watershed area). The ocean and large lakes/reservoirs were extracted from Global 1-second Water Body Map ver 1.0 [@yamazakiDevelopmentGlobal90m2015]. Watershed area was estimated based on the delineated watershed polygons. We estimated branching probability by fitting exponential distributions to histograms of branch length as $branch~length \sim Exp(\lambda)$ (unit: kilometer, river segment between successive confluences or a confluence and the outlet/upstream terminal). A derived statistical quantity $1  e^{\lambda}$ corresponds to the theoretical branching probability $P_b$.

We estimated the spatial averages of elevation, mean annual air temperature and cumulative precipitation for each watershed polygon, which were extracted from Hydrologically Adjusted Elevations of MERIT Hydro [@yamazakiMERITHydroHighResolution2019] and WorldClim 1.4 [@hijmansVeryHighResolution2005]. The fractions of forest, urban, and agriculture were calculated based on land use data in 2015 from Copernicus Global Land Service (100-m resolution) [@marcelbuchhornCopernicusGlobalLand2020]. The Global Reservoir and Dam Database, Version 1 (GRanDv1) [@lehnerGlobalReservoirDam2011] was used to estimate dam density per unit watershed area (km^-2^). We used ArcMap 10.7, SAGA 6.3.0, and the following R packages to perform geospatial analysis: 'RSAGA' [@brenningRSAGASAGAGeoprocessing2018], 'sf' [@pebesmaSimpleFeaturesStandardized2018] 'raster' [@hijmansRasterGeographicData2020] 'stars' [@pebesmaStarsSpatiotemporalArrays2020], and 'exactextractr' [@bastonExactextractrFastExtraction2020].

### Statistical analysis

We developed robust regression models with an M-estimation method to examine power laws of riverine biodiversity. The robust regression analysis is insensitive to outliers of a response variable; therefore, this method allows us to account for uncertainties of our diversity estimates (see **Fish community data**). Log-transformed diversity metrics ($\alpha$, $\beta$ and $\gamma$ diversity) at watershed $w$, $log_{10}~y_w$, were assumed to follow a normal distribution as $log_{10}~y_w \sim Normal(\mu_w, \sigma^2)$. The parameter $\mu_w$ was related to linear predictors, including log-transformed watershed area (ecosystem size; $log_{10}~A$), log-transformed branching probability (ecosystem complexity; $log_{10}~P_b$), region (coded as Hokkaido = 0, Midwest = 1; $region$), air temperature, precipitation, the fraction of agricultural land use (logit-transformed), and dam density. Although our primary focus of this analysis is to assess the effects of watershed area and branching probability, we included climate and land use variables to control their effects statistically. We did not include the fractions of urban and forest land use in the statistical models because these variables were strongly correlated with the fraction of agricultural land use (**Figure S19**). Similarly, we did not use mean elevation in the statistical models because it showed a moderate correlation with air temperature (**Figure S19**). Correlations for other combinations of explanatory variables were weak to moderate.

Climate (air temperature and precipitation) and land use (the fraction of agricultural land use and dam density) differed clearly between the regions. Therefore, we used residuals of the simple linear regressions between the climate or land use variable (response variable) and region (explanatory variable). The residuals represent deviations from the regional averages; positive values indicate values greater than the regional average while negative values indicating values smaller than the regional average.

We constructed two models for each of the diversity metrics: global and region-specific models. The global model assumes that the effects of watershed area and branching probability are consistent across geographic regions (i.e., no interactive effects of the region with other linear predictors).

$$
\begin{aligned}
\mu_w = \xi_0 + \xi_1~log_{10}~A_w + \xi_2~log_{10}~P_{b,w} + \xi_3~region_w + \sum_k \xi_k x_{k,w} &\text{(9)}
\end{aligned}
$$

where $\xi_k$ are the intercept and regression coefficients for linear predictors. In an ordinary scale, the global model represents a dual scaling law as $E(y) = cA^{\xi_1}P_b^{\xi_2}$, where $c = 10^{\xi_0 + \xi_3region + \sum_k \xi_k x_{k}}$. Meanwhile, the region-specific model assumes the effects of watershed area and branching probability differ between regions (i.e., interactions between region and watershed area/branching probability).

$$
\begin{aligned}
  \mu_w =& \xi_0 + \xi_1~log_{10}~A_w + \xi_2~log_{10}~P_{b,w} + \xi_3~region_w + &&\\
  &\xi_4~log_{10}~A_w \cdot region_w + \xi_5~log_{10}~P_{b,w} \cdot region_w + \sum_k \xi_k x_{k,w}
&&\text{(10)}
\end{aligned}
$$

This is equivalent to:

$$
\begin{aligned}
  \mu_w =& \xi_0 + (\xi_1 + \xi_4~region_w)~log_{10}~A_w + (\xi_2 + \xi_5~region_w)~log_{10}~P_{b,w} + &&\\
  &\xi_3~region_w + \sum_k \xi_k x_{k,w}
&&\text{(11)}
\end{aligned}
$$

Therefore, in an ordinary scale, the model assumes different scaling exponents between regions as $E(y) = cA^{\xi_1 + \xi_4region}P_b^{\xi_2 + \xi_5region}$. All explanatory variables except watershed area, branching probability, and region were standardized to a mean of zero and a standard deviation of one before the analysis.

We compared the performance of these competing models using the Bayes factor [@wagenmakersPracticalSolutionPervasive2007], which gives the relative strength of evidence in favor of the global model (M0) over the region-specific model (M1). We used Bayesian Information Criteria (BIC) of the linear models to approximate the Bayes factor [@wagenmakersPracticalSolutionPervasive2007]:

$$
\begin{aligned}
Bayes~factor = exp(\Delta BIC_{10}/2) &\text{(12)}
\end{aligned}
$$

where $\Delta BIC_{10} = BIC(M1) - BIC(M0)$.

For the supported model of $\gamma$ diversity, we estimated average predictive comparisons of watershed area and branching probability to compare their effect sizes. The average predictive comparison is an expected change of the response variable per a unit difference of the explanatory variable of interest [@gelmanAveragePredictiveComparisons2007]. Unlike other common metrics of effect size (e.g., standardized regression coefficients), this method provides intuitive yet rigorous estimates of effect size in models with non-linear variable transformations (see **Supporting Information** for further details). We performed statistical analysis using R version 4.1.0 [@rcoreteamLanguageEnvironmentStatistical2020].

# Acknowledgments

We are grateful to numerous people who have been involved in the collection of fish community data. We thank Michio Fukushima and Hirokazu Urabe for providing information on the Hokkaido Freshwater Fish Database HFish and the fish monitoring data at protected watersheds in Hokkaido. We thank Jacques Finlay for his constructive comments on the earlier version of the manuscript. This material is based upon work supported by the National Science Foundation through a Water Sustainability and Climate Program Observatory grant (EAR1209402): REACH (Resilience under Accelerated Change) and through the Division of Environmental Biology (DEB 2015634), Environmental Protection Agency through a Water Quality Benefits grant (EPA-G2015-STAR-A1), and the University of North Carolina at Greensboro through a start-up fund.

# Author contributions

AT conceived of the project. AT performed theoretical and statistical analysis with inputs from TK. AT, SK, CLD, and YM compiled and managed the fish community data set. AT wrote the first draft while SK, CLD, TK, and YM contributed significantly to the final version.

# Data and code availability

Third parties provided data for empirical data analysis; references are provided where appropriate. R functions for the generation of branching networks and the metacommunity simulation are provided as the R package 'mcbrnet' (available at <https://github.com/aterui/mcbrnet>). Codes for simulations, statistical analysis, figures, and tables are available at <https://github.com/aterui/public-proj_stream-diversity>.

# References
