---
title: "README"
output:
  github_document:
    toc: true
---

# Article Information

**Title**: Ecosystem size and complexity dictate riverine biodiversity

**Author**: Akira Terui, Seoghyun Kim, Christine L. Dolph, Taku Kadoya, Yusuke Miyazaki

# File Descriptions

See below or `metadata.html` (to view `metadata.html`, clone the repository and open `metadata.html` from your local computer). Note that original empirical data sets are not included in this repository because they were provided by third parties.

## Directory `theory`

Directory for theoretical data analysis.

-   `analysis_sensitivity` - regressions for simulation results of sensitivity analysis
-   `figure_alpha_pattern` - figure for spatial patterns of local species richness (for Supplementary Information)
-   `figure_n_patch` - figure for relationships between diversity metrics and ecosystem size
-   `figure_n_patch_si` - figure for relationships between diversity metrics and ecosystem size (for Supplementary Information)
-   `figure_p_branch` - figure for relationships between diversity metrics and ecosystem complexity
-   `figure_p_branch_si` - figure for relationships between diversity metrics and ecosystem complexity (for Supplementary Information)
-   `run_sensitivity_analysis` - run metacommunity simulations for sensitivity analysis
-   `run_simulaiton_alpha_pattern` - run metacommunity simulations for spatial patterns of local species richness (for Supplementary Information)
-   `run_simulation` - run metacommunity simulations
-   `table_sensitivity_analysis` - table for the results of sensitivity analysis
-   `table_sim_parameter_main` - table for parameters used in main simulations
-   `table_sim_parameter_sensitivity` - table for parameters used in sensitivity analysis
-   `/result` - subdirectory for simulation results
    -   `result_sim2020-11-10.csv` - results of main metacommunity simulation</summary>
    -   `result_sim_alpha_pattern2021-01-20.csv` - results of supplementary simulation (local diversity patterns)</summary>
    -   `result_sensitivity.csv` - results of sensitivity analysis</summary>

## Directory `empirical`

Directory for empirical data analysis.

-   `analysis_apcomp` - average predictive comparisons
-   `analysis_iNEXT_sim` - sensitivity simulation for the iNEXT function (Chao 2 estimator)
-   `analysis_lm_bf` - main analysis for influences of environmental variables on diversity metrics
-   `data_merge_hkd` - merge fish and GIS data in Hokkaido, Japan
-   `data_merge_mw` - merge fish and GIS data in Midwest, US
-   `figure_correlation` - correlation structure for potential explanatory variable (Supplementary Information)
-   `figure_diversity` - figure for relationships between biodiversity and ecosystem properties
-   `figure_iNEXT_sim` - figure for sensitivity analysis of the iNEXT function
-   `figure_map` - figure for maps
-   `table_apcomp` - table for average predictive comparisons
-   `table_sim_parameter_main` - table for parameter values of main simulations
-   `table_splist_hkd`; table for the fish species list in Hokkaido, Japan
-   `table_splist_mw` - table for the fish species list in Midwest, US
-   `/data_gis` - subdirectory for raw gis data
    -   `albers_channel_hkd` - channel network for Hokkaido
    -   `albers_channel_mw` - channel network for Midwest
    -   `albers_hkd_shape` - polygon for Hokkaido
    -   `albers_mw_shape` - polygon for Midest (HUC)
    -   `albers_point_subset_hkd` - subset of sampling points for Hokkaido
    -   `albers_point_subset_mw` - subset of sampling points for Midwest
    -   `albers_watershed_hkd_final` - watershed polygons for Hokkaido
    -   `albers_watershed_mw_final` - watershed polygons for Midwest
    -   `albers_wsd_subset_hkd` - subset of watershed polygons for Hokkaido
    -   `albers_wsd_subset_mw` - subset of watershed polygons for Midwest
-   `/result` - subdirectory for simulation output of the iNEXT sensitivity analysis
