---
title: "Table"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
  
  knitr::opts_knit$set(root.dir = here::here("empirical"))

```


```{r, echo = FALSE, message=FALSE, results='asis'}

source(here::here("/empirical/analysis_lm_bf.R"))

stargazer::stargazer(fit$alpha$model, fit$beta$model, fit$gamma$model,
                     header = FALSE,
                     type = "latex",
                     ci = TRUE,
                     title = "Estimated parameters of linear regression models explaining fish species richness in the Hokkaido (Japan) and the Midwest (US) regions. The 95\\% confidence intervals are shown in parenthesis. Dependent variables were log-10 transformed. Climate and land use variables (air temperature, precipitation, logit fraction of forest, dam density) are deviations from the regional averages and were standardized to a mean of zero and a standard deviation of one prior to the analysis.",
                     covariate.labels = c("$log_{10}$ Watershed area",
                                          "$log_{10}$ Branching probability",
                                          "Region (Midwest vs. Hokkaido)",
                                          "Air temperature",
                                          "Precipitation",
                                          "Logit fraction of forest",
                                          "Dam density",
                                          "Intercept"),
                     single.row = FALSE,
                     digits = 2,
                     dep.var.labels.include = FALSE,
                     column.labels = c("$\\alpha$ diversity", "$\\beta$ diversity", "$\\gamma$ diversity"),
                     keep.stat = c("rsq"),
                     model.numbers = FALSE)

```



