---
title: "Ecosystem size and complexity dictate riverine biodiversity"
author:
- Akira Terui^[Department of Biology, University of North Carolina at Greensboro]
- Seoghyn Kim\footnotemark[1]
- Christine L. Dolph^[Department of Ecology, Evolution and Behavior]
output:
  html_notebook: default
  word_document: default
abstract: |
  |This is the abstract.
bibliography: reference.bib
csl: nature.csl
---

```{r setup, include=FALSE}

pacman::p_load(tidyverse, sf)

## read gis files
filename <- list.files(path = normalizePath('../empirical/data_gis'), full.names = T)
wsd_subset <- lapply(filename[str_detect(filename, "wsd_subset")], st_read)
point_subset <- lapply(filename[str_detect(filename, "point_subset")], st_read)
shape <- lapply(filename[str_detect(filename, "shape")], st_read)
shape[[1]] <- st_set_crs(shape[[1]], st_crs(wsd_subset[[1]]))

## read theory file
dat_sim <- read_csv(normalizePath('../theory/result/result_sim2020-11-10.csv'))

n_scenario <- dat_sim %>% distinct(n_species,
                     mean_env_source,
                     sd_env_source,
                     rho,
                     asymmetry_factor,
                     min_optim,
                     max_optim,
                     sd_env_lon,
                     theta,
                     K0,
                     sd_env,
                     spatial_env_cor,
                     phi,
                     min_niche_width,
                     max_niche_width,
                     niche_cost,
                     p_dispersal,
                     min_alpha,
                     max_alpha) %>% 
  nrow()

source(normalizePath('../empirical/analysis_lm_bf.R'))

```

Ecologists have long sought to understand the general drivers of biodiversity. One of the most robust empirical generalizations in ecology is the positive relationship between species richness and area, i.e., the species-area relationship (the SAR)[@lomolinoEcologyMostGeneral2000a]. In 1921, Arrhenius[@arrheniusSpeciesArea1921] formulated the SAR as a power-law $S = cA^z$ ($S$ is the number of species observed in a given geographic area $A$), an equation currently known as the Arrhenius species-area relationship. Since then, the spatial scaling of species richness has been observed in nearly all taxonomic groups[@triantisIslandSpeciesArea2012], although the underlying mechanisms are still hotly debated[@ben-hurDisentanglingMechanismsUnderlying2020]. The SAR is ubiquitous because multiple mechanisms produce an apparently similar pattern. Larger ecosystems typically support more diverse metacommunities due to increased habitat diversity[@kallimanisHowDoesHabitat2008a], larger metacommunity size[@ben-hurDisentanglingMechanismsUnderlying2020;@hubbellUnifiedNeutralTheory2001], and/or enhanced colonization dynamics[@lososTheoryIslandBiogeography2009]. Importantly, the SAR provides the foundation for global conservation efforts. For example, conservation ecologists have used the SAR estimates to design marine and terrestrial protected areas, which currently encompass more than 30 million km² globally.

Many ecosystems, however, possess complex spatial structure that cannot be represented by area - a dimension referred to as the scale-invariant complexity[@rinaldoEvolutionSelectionRiver2014; @rodriguez-iturbeFractalRiverBasins2001]. Such complexity is evident in branching ecosystems, including rivers, trees, and mountain ranges, to name just a few[@rodriguez-iturbeFractalRiverBasins2001]. Geomorphic or biological processes generate a pronounced self-similarity in complex branching patterns such that the part and the whole look alike[@rodriguez-iturbeFractalRiverBasins2001]. Even though the branching structure is independent of spatial scale, it forms a physical template that dictates habitat diversity and dispersal corridors for living organisms[@grantLivingBranchesPopulation2007; @rinaldoRiverNetworksEcological2018;@tonkinRoleDispersalRiver2018]. Limited, but accumulating evidence suggests that classical concepts cannot predict ecological dynamics driven by branching structure[@faganConnectivityFragmentationExtinction2002; @grantUseMultipleDispersal2010; @teruiMetapopulationStabilityBranching2018], and this recognition has led to recent developments of spatial theories devoted to complex branching ecosystems[@altermattDiversityRiverineMetacommunities2013; @carraraComplexInteractionDendritic2014; @carraraDendriticConnectivityControls2012; @teruiMetapopulationStabilityBranching2018]. However, most research either has explored the consequences of branching complexity for local variation in species richness or relied on theoretical arguments with limited replicates of artificial branching networks. At present, we lack a comprehensive evaluation of how branching complexity, in combination with ecosystem size, scales biodiversity at the metacommunity level. Filling this knowledge gap may provide common ground for achieving successful conservation in spatially complex ecosystems, where the accelerated species loss threatens the delivery of ecosystem services.

Here, we hypothesize that ecosystem size and complexity dictate biodiversity patterns in rivers, a prime example of complex branching ecosystems.
The recurrent merging of diverse streams and rivers produces larger, ecologically distinct channels, ultimately forming a fluvial network with fractal branching patterns[@rodriguez-iturbeFractalRiverBasins2001]. As such, the complexity of branching structure, which we define here as the probability of branching per unit river distance [@teruiMetapopulationStabilityBranching2018; @yeakelSynchronisationStabilityRiver2014a], should control the habitat heterogeneity of the ecosystem (habitat diversity per unit area). Meanwhile, ecosystem size (watershed area) should determine the metacommunity size and total habitat diversity (area x heterogeneity). We predict that ecosystem size and branching complexity increase $\gamma$ diversity by enhancing either $\alpha$ and/or $\beta$ diversity under different ecological scenarios. The present study combines theory and statistical analysis of extensive community data to provide crucial insights into how ecological communities are structured in complex branching networks.

First, we theoretically analyzed the influences of ecosystem size and branching complexity on $\gamma$ diversity. We constructed a general simulation model of metacommunity dynamics [@thompsonProcessbasedMetacommunityFramework2020], in which 50 competing species disperse and spatially interact in a random branching network. Simulated species with different niche in abiotic conditions (optimum and width) compete for resources with varied strengths. For simplicity, other ecological traits, such as dispersal probability, are assumed to be identical among species. Here, we depicted branching ecosystems as a spatial network of connected habitat patches (or a discretized river section; see **Figure 1**) where mean environmental conditions at each habitat patch are determined by two factors: (1) the headwater environments (the most upstream habitat patch) and (2) local environmental noise. Environmental values at the headwaters are drawn randomly from a normal distribution and propagates downstream with local environmental noise (i.e., the spatial autoregressive process with white noise). These environmental values recurrently 'mix' at confluences considering the relative size of joining tributaries (see Methods). Therefore, our simulation resembles natural processes of how branching river networks create diverse habitats in a metacommunity. We used `r n_scenario` sets of parameter combinations with varied ecological (dispersal and competition strength) and landscape scenarios (the environmental variation at headwaters and the degree of local environmental noise). Under each scenario, we simulated metacommunity dynamics in `r max(dat_sim$n_rep)` branching networks that have different ecosystem size (the number of habitat patches: `r min(dat_sim$n_patch)` to `r max(dat_sim$n_patch)`) and complexity (branching probability: `r round(min(dat_sim$p_branch), 2)` to `r round(max(dat_sim$p_branch), 2)`) to examine their effects on species diversity.

Our theoretical analysis yielded results consistent with our prediction. Ecosystem size and complexity both increased $\gamma$ diversity under a realistic landscape scenario (**Figures 2 and 3**), where the environmental variation at headwaters ($\sigma_h$) is greater than the degree of local environmental noise ($\sigma_l$) [@petersonModellingDendriticEcological2013; @teruiMetapopulationStabilityBranching2018]. The relationships had a characteristic of power-law (i.e., linear in a log-log scale) and were consistent under various ecological scenarios. The strength of competition and dispersal processes (dispersal distance and probability) did not change the form of the relationships between $\gamma$ diversity and ecosystem properties. Hence, the ecosystem size and complexity are both expected to increase $\gamma$ diversity regardless of ecological scenarios.

Dispersal processes, however, affected underlying mechanisms that produce the positive effects of ecosystem size and complexity on $\gamma$ diversity. We observed a greater contribution of $\beta$ diversity (defined as $\frac{\gamma}{\alpha}$) to increased $\gamma$ diversity when dispersal limitation exists (i.e., species travel short distances). This pattern reflects significant spatial turnover of species composition over the branching network. In contrast, once the dispersal limitation was relaxed (species travel long distances), a clear increase in $\alpha$ diversity underpinned the positive relationships between $\gamma$ diversity and ecosystem properties. The results agree with previous predictions that increased dispersal homogenizes community composition while enhancing local diversity through increased immigrants from suitable habitat patches (i.e., mass effects)[@thompsonProcessbasedMetacommunityFramework2020]. These patterns were consistent across different levels of dispersal probabilities (**cite SI figure**). The strength of competition decreased maximum levels of $\alpha$ diversity but did not change the functional forms of the scaling relationships with ecosystem properties (**Figures 2 and 3**). In summary, our theory highlights how the apparently similar patterns in $\gamma$ diversity emerges through different ecological pathways.

Influences of ecosystem size and complexity differed significantly in their dependence on landscape scenarios. Ecosystem size had positive effects on $\gamma$ diversity regardless of landscape scenarios, although the slopes were steeper with greater environmental variation (higher $\sigma_h$ and/or $\sigma_l$). This result is attributable to the fact that larger ecosystems can hold more individuals in a metacommunity[@hubbellUnifiedNeutralTheory2001]. In contrast, we observed limited or no influences of branching complexity when local environmental noise was equal to or exceeded environmental variation at headwaters ($\sigma_l \ge \sigma_h$). Under this scenario, having more branches may not contribute to the habitat diversity in the ecosystem because local environmental noise masks environmental differences between branches. Therefore, this landscape scenario decouples the intimate relationship between branching structure and habitat diversity, thereby eliminating the positive effect of branching complexity on $\gamma$ diversity. This theoretical prediction may not apply to pristine to semi-natural river networks where individual streams with diverse geological and/or climatic backgrounds show distinct environmental conditions, including water temperature, water chemistry, substrate, and flow/sediment regimes. Instead, it may be more relevant to severely altered landscapes where human disturbance compromises the environmental distinctiveness of each branch through, for example, flow regulations by dams. Hence, our theory has important implications for riverine biodiversity conservation by pointing the crucial role of habitat diversity produced by branching structure[@holtRoleBranchingMaintenance2018].

The proposed theory provided important insights into how ecological communities are structured in branching networks; however, empirically testing the predictions is extremely difficult because it requires metacommunity-level replications. To confront this logistical challenge, we compiled existing community data of fishes from a variety of sources and developed a unique large dataset that spans across two geographic regions: the Hokkaido island in Japan and the Midwest in the United States. These regions are located in comparable ranges of latitude but support distinct fish communities. Therefore, this dataset provides an excellent opportunity to examine the generality of our theoretical predictions. After careful data selection, we estimated $\alpha$, $\beta$, and $\gamma$ diversity (asymptotic species richness; Methods) at `r nrow(wsd_subset[[1]]) + nrow(wsd_subset[[2]])` watersheds (`r nrow(wsd_subset[[1]])` in Hokkaido and `r nrow(wsd_subset[[2]])` in Midwest), each of which comprised $\ge$ 10 sites of presence-absence fish community data (a total of `r nrow(point_subset[[1]]) + nrow(point_subset[[2]])` sites). Individual watersheds, i.e., metacommunity replicates in our analysis, were considered as separated if they flow into one of the following: the ocean, a large lake ($\ge$ 10 km² in the areal area) or a large river that may represent lentic habitats ($\ge$ 5000 km² in the watershed area). We combined this dataset with geospatial information (watershed area, branching probability, annual mean temperature, annual cumulative precipitation, and percent forest) to examine potential influences of macro-scale drivers of species diversity. Using this dataset, we developed global and region-specific models for each of diversity measures ($\alpha$, $\beta$, and $\gamma$ diversity) to examine whether observed patterns are consistent across the two geographic regions. In the global model, we assumed that effects of ecosystem size (watershed area) and complexity (branching probability) are constant across the two regions (i.e., fixed slopes). Meanwhile, the region-specific model assumes region-specific slopes of ecosystem size and complexity by including interaction terms with the dummy binary variable of region (Hokkaido = 0; Midwest = 1). We compared the performance of these competing models using the Bayes factor, a measure of the strength of evidence in favor of one model over the alternative.

Despite the substantial difference in fish fauna between the study regions, the estimated Bayes factor in favor of the global model explaining $\gamma$ diversity was `r round(fit$gamma$bayes_factor, 1)`; this result strongly supports the consistent effects of ecosystem size and complexity on $\gamma$ diversity across the two biogeographic regions. Further, we found patterns consistent with our theoretical predictions. The estimated $\gamma$ diversity increased with increasing watershed area (ecosystem size) and branching probability (ecosystem complexity) across watersheds. These effects remained significant even after controlling for the potential influences of other environmental factors (precipitation, temperature, and land use). Overall, our statistical analysis provides strong empirical evidence that ecosystem size and complexity jointly, but independently, scale riverine biodiversity at the metacommunity level.

Similarly, we found weak to moderate supports for the global models explaining observed patterns of $\alpha$ and $\beta$ diversity (Bayes factor: `r round(fit$alpha$bayes_factor, 1)` and `r round(fit$beta$bayes_factor, 1)`, respectively). In both regions, $\beta$ diversity responded significantly to ecosystem size and complexity. In our simulations, this pattern has emerged under the scenarios with dispersal limitation, which elegantly match the previous observations of stream fish movement. Direct (mark-recapture) and indirect observations (e.g., genotyping) recurrently revealed restricted movement of stream fish, typically limited to several tens to hundreds of meters in distance[@comteFishDispersalFlowing2018; @radingerPatternsPredictorsFish2014; @rodriguezRestrictedMovementStream2002]. The reciprocal agreement of theoretical and empirical patterns provides indirect but convincing evidence that dispersal limitation plays a key role in driving the associations between $\gamma$ diversity and ecosystem properties in rivers.

The consistent effect of branching probability on $\gamma$ diversity across the study regions is noteworthy because the watersheds in the Midwest are severely altered by agriculture (median % agricultural land use: `r round(median(wsd_subset[[2]]$frac_agri)*100)`% for Midwest and `r round(median(wsd_subset[[1]]$frac_agri)*100)`% for Hokkaido). If the intensive land use by humans causes significant homogenization of in-stream habitat conditions among tributaries, theory predicts weakened effects of branching probability on $\gamma$ diversity. However, $\gamma$ diversity increased significantly with increasing branching probability in this highly modified landscape, suggesting that tributaries still sustain unique environmental conditions to support high spatial trunover of species composition. In support of this interpretation, $\beta$ diversity increased with increasing branching probability in both regions (**Figure 4**). It is conceivable that local geological and geomorphological differences, such as slope, aspect, and soil porosity, still persist in human-dominated landscapes to maintain diversity of in-stream processes among tributaties[@bendaNetworkDynamicsHypothesis2004]. Although our analysis is correlative and cannot provide conclusive evidence, the finding is encouraging because branching complexity of river networks may serve as a natural defense system to human-induced environmental changes.

There may be confounding factors that are not incorporated in our statistical models. However, we are confident on our statistical inference because the observed patterns were fairly consistent with our theoretical predictions that are free from any confounding effects. Further, our fitted models generally showed high R^2^ values ($\alpha$ diversity: `r round(summary(fit$alpha$model)$r.squared, 2)`; $\beta$ diversity, `r round(summary(fit$beta$model)$r.squared, 2)`; $\gamma$ diversity `r round(summary(fit$gamma$model)$r.squared, 2)`) with no signs of spatial autocorrelation in residuals. Therefore, it is very unlikely that our results were driven by spurious correlations.

The emerging complexity-diversity relationship points to several important avenues for riverine biodiversity conservation. First and foremost, there is now a clear need to explicitly consider the dimension of ecosystem complexity to achieve successful conservation. Human alterations, including flow regulation[@poffHomogenizationRegionalRiver2007], habitat fragmentation, and stream burial, may compromise or restrict access to the diverse habitats that complex branching networks may provide. Hence, it is imperative to recognize the role of branching complexity and minimize the homogenizing effects of human alterations. Second, the complexity perspective may provide viable options to reconcile conflicts between biodiversity conservation and societal needs. Although protected areas spearhead global conservation efforts, habitat preservation and restoration over large areas are often impractical because of conflicts with stakeholders. This is particularly true for riverine ecosystems, where numerous stakeholders are involved within a single watershed and enormous efforts are required to reach consensus[@palmerEcologicalRestorationStreams2014]. In such a scenario, spatial planning of small-scale conservation, such as restoration of connectivity to small tributaties, may be critical to enhancing the 'realized' network complexity that organisms may experience. Our theoretical framework may be used to design spatial arrangement of small-scale conservation that improves ecological outcomes at the metacommunity level.

While the prevailing evidence supports the importance of ecosystem size in scaling species diversity, ecosystem complexity - especially branching structure - has not received the attention it deserves. Ecosystems are inherently complex in its spatial structure, providing a physical template that creates a wide spectrum of niche opportunities for living organisms. Hence, our findings should be broadly applicable to many taxa and ecosystems. Generalization of the complexity perspective is a frontier for future research.


# Methods

## Theoretical branching networks

We depicted branching ecosystems as a spatial network of connected habitat patches. Habitat patches can be either non-branching or branching river sections with a unit length $l$, which defines the scale of local species interactions. Two parameters determine geometric properties of simulated branching networks: the number of habitat patches $N_p$ (ecosystem size) and branching probability $P_b$ (ecosystem complexity). Each habitat patch is assigned to be a branching patch (including upstream terminals) with probability $P_b$ or non-branching patch with probability $1-P_b$. In this framework, an individual branch is a consecutive series of non-branching patches terminated at a branching patch; therefore, the number of habitat patches in a single branch $n_b$ is a realization of a random variable drawn from a geometric distribution $n_{b} \sim Ge(P_{b})$. This representation has two merits. First, it reflects observed patterns of branch length distribution, which is known to follow an exponential distribution (a continuous version of a geometric distribution). Second, it preserves the fractal nature of branching patterns[@peckhamReformulationHortonLaws1999].

The long-term average of abiotic environment $\mu_z$ at each habitat patch is characterized by two sources of variation: environmental variation at headwaters ($\sigma_h$) and local environmental noise ($\sigma_l$). We draw random values from a normal distribution with a mean of zero and SD of $\sigma_{h}$ and assigned them to headwater patches (i.e., the most upstream patches). These environmental values at headwaters propagate downstream through a spatial autoregressive process defined as:

$$
\mu_{z,k} = \rho \mu_{z,k+1} + \epsilon_{k}
$$

where $\mu_{z,k}$ is the environmental value at longitudinal position $k$ ($k$ is the network distance from the outlet patch; $k = 1$ at the outlet), $\rho$ is the strength of spatial autocorrelation and $\epsilon_k$ is the local environmental noise that follows a normal distribution with a mean of zero and SD of $\sigma_l$. The parameter $\rho$ can take values of $0-1$ with larger values indicating greater spatial autocorrelation. In this study, we set $\rho = 1$ to mimic strong spatial autocorrelation in rinverine environments. At confluences, we took a weighted mean of environmental values given the relative size of upstream contributing area of joining tributaries:

$$
\begin{align}
\mu_{z,k} &= \omega(\rho \mu_{z,k+1}^R + \epsilon_{k}^R) + (1-\omega)(\rho \mu_{z,k+1}^L + \epsilon_{k}^L) \\
\omega &= \frac{A_{k+1}^R}{A_{k+1}^R + A_{k+1}^L}
\end{align}
$$
where $R$ and $L$ denote "right" and "left" branches, respectively, and $A_k$ is the number of upstream habitat patches at patch $k$ (akin to upstream watershed area). With this expression, larger tributaties have a greater influence on the downstream environment, as observed in natural river networks[@bendaNetworkDynamicsHypothesis2004].

## Metacommunity model
We simulated metacommunity dynamics in branching river networks following the metacommunity framework proposed by Thompson et al.[@thompsonProcessbasedMetacommunityFramework2020]. In this framework, abiotic environmental conditions (density independent), intra- and interspecific competition (density dependent), and dispersal regulate the realized population growth of a species. Below, we describe details of our metacommunity model.

The realized number of individuals $N_{ix}(t + 1)$ (species $i$ at patch $x$ and time $t+1$) is given as:

$$
N_{ix}(t + 1) \sim Poisson(n_{ix}(t) + I_{ix}(t) - E_{ix}(t))
$$
where $n_{ix}(t)$ is the expected number of individuals given the local community dynamics at time $t$, $I_{ix}(t)$ the expected number of immigrants to patch $x$, and $E_{ix}(t)$ the expected number of emigrants from patch $x$. The realized discrete number of individuals is drawn from a Poisson distribution to account for stochasticity in demographic and dispersal processes[@fronhoferClassicalMetapopulationDynamics2017; @thompsonProcessbasedMetacommunityFramework2020]. Local community dynamics are simulated based on the Beverton-Holt equation:

$$
n_{ix}(t) = \frac{N_{ix}(t)r_{ix}(t)}{1 + \frac{r_{0,i}-1}{K_{x}}\sum_{j=1}^S{\alpha_{ij}N_{jx}(t)}}
$$

where $r_{ix}(t)$ is the reproductive rate of species $i$ given the environmental condition at patch $x$ and time $t$, $r_{0,i}$ the maximum reproductive rate of species $i$, $K_{x}$ the carrying capacity at patch $x$, $\alpha_{ij}$ the interaction coefficient between species $i$ and $j$, and $S$ the number of species in a metacommunity. The parameter $\alpha_{ij}$ is expressed as the strength of interspecific competition relative to that of intraspecific competition such that interspecific competition is greater than intraspecific competition if $\alpha_{ij}$ > 1 (intraspecific competition coefficient $\alpha_{ii} = 1$). The density-independent reproductive rate $r_{ix}(t)$ is affected by abiotic environments (non-consumable) and determined by the following Gaussian function:

$$
r_{ix}(t) = cr_{0,i}~exp[{-\frac{(\mu_i-z_x(t))^2}{2\sigma^2_{niche,i}}}]
$$
where $\mu_i$ is the optimal environmental value for species $i$, $z_x(t)$ the environmental value at patch $x$ and time $t$, and $\sigma_{niche}$ the niche width of species $i$. Species with wider niche (greater values of $\sigma_{niche}$) should always have greater competitive ability in the absence of the cost of wide niche. Therefore, we introduced the cost of wide niche by multiplying $c$[@chaianunpornEvolutionaryResponsesClimate2015]:

$$
c = exp(-\frac{\sigma_{niche,i}^2}{2\nu^2})
$$ 

Smaller values of $\nu$ imply greater costs of having wider niche (i.e., decreased maximum reproductive rate) and reduce the realized reproductive rate $r_{ix}(t)$.

The environmental value at patch $x$ and time $t$, $z_x(t)$, is assumed to follow a multivariate normal distribution as $z_{x}(t) \sim MVN(\mu_z, \Omega_z)$. $\mu_z$ is the vector of mean environmental conditions of patches and $\Omega_z$ is the variance-covariance matrix. Spatial autocorrelation in temporal environmental dynamics is considered by expressing the off-diagonal elements as:

$$
\Omega_{xy} = \sigma_z^2~exp(-\phi d_{xy})
$$

where $\Omega_{xy}$ denotes the temporal covariance of environmental conditions between patch $x$ and $y$, which is assumed to decay exponentially with increasing distance between the patches $d_{xy}$. The parameter $\phi$ determines the degree of distance decay of environmental correlates.

The expected number of emigrants at time $t$ is the product of dispersal probability $p_d$ and $n_{ix}(t)$: $E_{ix}(t) = p_{d}n_{ix}(t)$. The immigration probability at patch $x$ for species $i$, $\xi_{ix}(t)$, is calculated using the following equation that accounts for separation distance among habitat patches and dispersal capability of a species:

$$
\xi_{ix}(t) = \frac{\sum_{y,y \neq x}E_{iy}(t)~exp(-\theta d_{xy})}{\sum_{x} \sum_{y,y \neq x}E_{iy}(t)~exp(-\theta d_{xy})}
$$
where $d_{xy}$ is the separation distance between patch $x$ and $y$. The parameter $\theta$ regulates the dispersal distance of a species that follows an exponential distribution ($\theta^{-1}$ corresponds to the expected dispersal distance). The expected number of immigrants is calculated as $I_{ix}(t) = \xi_{ix}(t)\sum_x^{N_p} E_{ix}$.

## Simulation
We used `r n_scenario` sets of parameter combinations to produce different landscape (four patterns of habitat heterogeneity) and ecological scenarios (eight patterns of dispersal and competition). To create landscape scenarios with different patterns of habitat heterogeneity, we varied environmental variation at headwaters ($\sigma_h$) and the degree of local environmental noise ($\sigma_l$) separately. Larger values of $\sigma_h$ and/or $\sigma_l$ produce greater variation in environmental conditions among habitat patches. We used two values for each of the SD parameters ($\sigma_h =$ `r unique(dat_sim$sd_env_source)` and $\sigma_l =$ `r unique(dat_sim$sd_env_lon)`), resulting in four sets of parameter combinations. When $\sigma_h > \sigma_l$, having more tributaries in a network exhibits important effects on overall habitat diversity as branching is the primary source of environmental variation. When $\sigma_h \le \sigma_l$, local environmental noise masks environmental variation among tributaries, leading to minimal influences of branching on overall habitat diversity in a network. For ecological scenarios, we varied three ecological parameters that are relevant for dispersal and interspecific competition: dispersal distance ($\theta =$ `r unique(dat_sim$theta)`), dispersal probability ($p_d =$ `r unique(dat_sim$p_dispersal)`), and the maximum value of competition coefficients ($\alpha_{max} =$ `r unique(dat_sim$max_alpha)`). This setup results in eight ecological scenarios with different levels of dispersal and competition.

We used fixed values for the following parameters: maximum reproductive number ($r_{0,i} =$ 4), niche cost ($\nu =$ `r unique(dat_sim$niche_cost)`), the degree of temporal fluctuation in abiotic environments ($\sigma_z =$ `r unique(dat_sim$sd_env)`), and the degree of spatial autocorrelation in temporal environmental dynamics ($\phi =$ `r unique(dat_sim$phi)`).

## Empirical data
We compiled fish data at two biogeographic regions: Hokkaido island, Japan and Midwest, US. For Hokkaido, we used data from the Hokkaido Freshwater Fish Database HFish, monitoring data at protected watersheds, and primary data collected by the authors. Collectively, these fish data encompass more than 7000 sites and covers the entire Hokkaido island. For the Midwest, we assembled fish community data collected by XXX.

We selected data based on the following criterion. First, we reviewed 



# References
