---
title: "Figures"
output:
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

```

```{r, fig.height=6, fig.width=8, fig.cap="Theoretical predictions for ecosystem size influences (the number of habitat patches) on $\\alpha$, $\\beta$, and $\\gamma$ diversity in branching networks. Lines and shades are loess curves fitted to simulated data and its 95% confidence intervals. Each panel represents different ecological scenarios under which metacommunity dynamics were simulated. Rows represent different competition strength. Competitive coefficients ($\\alpha_{c}$) were varied randomly from 0 to 1.5 (top, strong competition) or 0.75 (bottom, weak competition). Columns represent different dispersal scenarios. Two dispersal parameters were chosen to simulate scenarios with long-distance (the rate parameter of an exponential dispersal kernel $\\theta = 0.10$) and short-distance dispersal ($\\theta = 1.0$). In this simulation, environmental variability among headwaters (i.e., the most upstream patches), which is expressed as the standard deviation of a normal distribution ($\\sigma_{h} = 1.0$), was greater than that of local environmental noise occurring at each habitat patch ($\\sigma_{l} = 0.01$). Dispersal probability $p_{d}$ was 0.01 for all the scenarios."}

source(normalizePath("../theory/figure_n_patch_si.R"))
n_patch_fig(p_dispersal = 0.01, sd_env_lon = 0.01, sd_env_source = 0.01)
```

\newpage

