
table_output <- tibble(Parameter = c('$\\sigma_{h}$',
                                     '$\\sigma_{l}$',
                                     '$\\sigma_{z}$',
                                     '$\\rho$',
                                     '$\\phi$',
                                     '$\\nu$',
                                     '$b_{max}$',
                                     '$\\theta$',
                                     '$p_{d}$',
                                     '$r_{0,i}$'),
                       Value = c('Unif(0.01, 1)',
                                 'Unif(0.01, 1)',
                                 'Unif(0.01, 0.5)',
                                 '1',
                                 'Unif(0.01, 1)',
                                 'Unif(1, 5)',
                                 'Unif(0.5, 1.5)',
                                 'Unif(0.1, 1)',
                                 'Unif(0.01, 0.1)',
                                 '4'),
                       Interpretation = c('Environmental variation at headwaters',
                                          'Degree of local environmental noise',
                                          'Temporal environmental variability',
                                          'Strength of spatial autocorrelation in mean environmental condition',
                                          'Extent of spatial autocorrelation in temporal environmental variation',
                                          'Cost of a wider niche',
                                          'Maximum value of interspecific competition coefficient',
                                          'Rate parameter of an exponential dispersal kernel',
                                          'Dispersal probability',
                                          'Maximum reproductive rate')) %>% 
                  kable(format = 'markdown')
